// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/table/table.proto

package table

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Physical/operational state of a table.
// Time-slot availability is owned by order-service, not this status.
type TableStatus int32

const (
	TableStatus_STATUS_UNKNOWN        TableStatus = 0
	TableStatus_STATUS_AVAILABLE      TableStatus = 1
	TableStatus_STATUS_CLEANING       TableStatus = 2
	TableStatus_STATUS_OUT_OF_SERVICE TableStatus = 3
)

// Enum value maps for TableStatus.
var (
	TableStatus_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_AVAILABLE",
		2: "STATUS_CLEANING",
		3: "STATUS_OUT_OF_SERVICE",
	}
	TableStatus_value = map[string]int32{
		"STATUS_UNKNOWN":        0,
		"STATUS_AVAILABLE":      1,
		"STATUS_CLEANING":       2,
		"STATUS_OUT_OF_SERVICE": 3,
	}
)

func (x TableStatus) Enum() *TableStatus {
	p := new(TableStatus)
	*p = x
	return p
}

func (x TableStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TableStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_table_table_proto_enumTypes[0].Descriptor()
}

func (TableStatus) Type() protoreflect.EnumType {
	return &file_proto_table_table_proto_enumTypes[0]
}

func (x TableStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TableStatus.Descriptor instead.
func (TableStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_table_table_proto_rawDescGZIP(), []int{0}
}

type Table struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableId       string                 `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	TableNumber   int32                  `protobuf:"varint,2,opt,name=table_number,json=tableNumber,proto3" json:"table_number,omitempty"`
	Capacity      int32                  `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Status        TableStatus            `protobuf:"varint,4,opt,name=status,proto3,enum=table.TableStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Table) Reset() {
	*x = Table{}
	mi := &file_proto_table_table_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_proto_table_table_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_proto_table_table_proto_rawDescGZIP(), []int{0}
}

func (x *Table) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *Table) GetTableNumber() int32 {
	if x != nil {
		return x.TableNumber
	}
	return 0
}

func (x *Table) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Table) GetStatus() TableStatus {
	if x != nil {
		return x.Status
	}
	return TableStatus_STATUS_UNKNOWN
}

func (x *Table) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Table) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateTableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableNumber   int32                  `protobuf:"varint,1,opt,name=table_number,json=tableNumber,proto3" json:"table_number,omitempty"`
	Capacity      int32                  `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTableRequest) Reset() {
	*x = CreateTableRequest{}
	mi := &file_proto_table_table_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTableRequest) ProtoMessage() {}

func (x *CreateTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_table_table_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTableRequest.ProtoReflect.Descriptor instead.
func (*CreateTableRequest) Descriptor() ([]byte, []int) {
	return file_proto_table_table_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTableRequest) GetTableNumber() int32 {
	if x != nil {
		return x.TableNumber
	}
	return 0
}

func (x *CreateTableRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

type CreateTableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         *Table                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTableResponse) Reset() {
	*x = CreateTableResponse{}
	mi := &file_proto_table_table_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTableResponse) ProtoMessage() {}

func (x *CreateTableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_table_table_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTableResponse.ProtoReflect.Descriptor instead.
func (*CreateTableResponse) Descriptor() ([]byte, []int) {
	return file_proto_table_table_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTableResponse) GetTable() *Table {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *CreateTableResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateTableResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetTableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableId       string                 `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTableRequest) Reset() {
	*x = GetTableRequest{}
	mi := &file_proto_table_table_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTableRequest) ProtoMessage() {}

func (x *GetTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_table_table_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTableRequest.ProtoReflect.Descriptor instead.
func (*GetTableRequest) Descriptor() ([]byte, []int) {
	return file_proto_table_table_proto_rawDescGZIP(), []int{3}
}

func (x *GetTableRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

type GetTableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         *Table                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTableResponse) Reset() {
	*x = GetTableResponse{}
	mi := &file_proto_table_table_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTableResponse) ProtoMessage() {}

func (x *GetTableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_table_table_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTableResponse.ProtoReflect.Descriptor instead.
func (*GetTableResponse) Descriptor() ([]byte, []int) {
	return file_proto_table_table_proto_rawDescGZIP(), []int{4}
}

func (x *GetTableResponse) GetTable() *Table {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *GetTableResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetTableResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateTableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableId       string                 `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	TableNumber   int32                  `protobuf:"varint,2,opt,name=table_number,json=tableNumber,proto3" json:"table_number,omitempty"`
	Capacity      int32                  `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTableRequest) Reset() {
	*x = UpdateTableRequest{}
	mi := &file_proto_table_table_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTableRequest) ProtoMessage() {}

func (x *UpdateTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_table_table_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTableRequest.ProtoReflect.Descriptor instead.
func (*UpdateTableRequest) Descriptor() ([]byte, []int) {
	return file_proto_table_table_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateTableRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *UpdateTableRequest) GetTableNumber() int32 {
	if x != nil {
		return x.TableNumber
	}
	return 0
}

func (x *UpdateTableRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

type UpdateTableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         *Table                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTableResponse) Reset() {
	*x = UpdateTableResponse{}
	mi := &file_proto_table_table_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTableResponse) ProtoMessage() {}

func (x *UpdateTableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_table_table_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTableResponse.ProtoReflect.Descriptor instead.
func (*UpdateTableResponse) Descriptor() ([]byte, []int) {
	return file_proto_table_table_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTableResponse) GetTable() *Table {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *UpdateTableResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateTableResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteTableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableId       string                 `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTableRequest) Reset() {
	*x = DeleteTableRequest{}
	mi := &file_proto_table_table_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTableRequest) ProtoMessage() {}

func (x *DeleteTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_table_table_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTableRequest.ProtoReflect.Descriptor instead.
func (*DeleteTableRequest) Descriptor() ([]byte, []int) {
	return file_proto_table_table_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteTableRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

type DeleteTableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTableResponse) Reset() {
	*x = DeleteTableResponse{}
	mi := &file_proto_table_table_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTableResponse) ProtoMessage() {}

func (x *DeleteTableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_table_table_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTableResponse.ProtoReflect.Descriptor instead.
func (*DeleteTableResponse) Descriptor() ([]byte, []int) {
	return file_proto_table_table_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteTableResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteTableResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListTablesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Status        TableStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=table.TableStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTablesRequest) Reset() {
	*x = ListTablesRequest{}
	mi := &file_proto_table_table_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTablesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTablesRequest) ProtoMessage() {}

func (x *ListTablesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_table_table_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTablesRequest.ProtoReflect.Descriptor instead.
func (*ListTablesRequest) Descriptor() ([]byte, []int) {
	return file_proto_table_table_proto_rawDescGZIP(), []int{9}
}

func (x *ListTablesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTablesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTablesRequest) GetStatus() TableStatus {
	if x != nil {
		return x.Status
	}
	return TableStatus_STATUS_UNKNOWN
}

type ListTablesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tables        []*Table               `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Success       bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTablesResponse) Reset() {
	*x = ListTablesResponse{}
	mi := &file_proto_table_table_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTablesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTablesResponse) ProtoMessage() {}

func (x *ListTablesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_table_table_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTablesResponse.ProtoReflect.Descriptor instead.
func (*ListTablesResponse) Descriptor() ([]byte, []int) {
	return file_proto_table_table_proto_rawDescGZIP(), []int{10}
}

func (x *ListTablesResponse) GetTables() []*Table {
	if x != nil {
		return x.Tables
	}
	return nil
}

func (x *ListTablesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListTablesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTablesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTablesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListTablesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateTableStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableId       string                 `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	Status        TableStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=table.TableStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTableStatusRequest) Reset() {
	*x = UpdateTableStatusRequest{}
	mi := &file_proto_table_table_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTableStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTableStatusRequest) ProtoMessage() {}

func (x *UpdateTableStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_table_table_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTableStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateTableStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_table_table_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateTableStatusRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *UpdateTableStatusRequest) GetStatus() TableStatus {
	if x != nil {
		return x.Status
	}
	return TableStatus_STATUS_UNKNOWN
}

type UpdateTableStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         *Table                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTableStatusResponse) Reset() {
	*x = UpdateTableStatusResponse{}
	mi := &file_proto_table_table_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTableStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTableStatusResponse) ProtoMessage() {}

func (x *UpdateTableStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_table_table_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTableStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateTableStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_table_table_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateTableStatusResponse) GetTable() *Table {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *UpdateTableStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateTableStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAvailableTablesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinCapacity   int32                  `protobuf:"varint,1,opt,name=min_capacity,json=minCapacity,proto3" json:"min_capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableTablesRequest) Reset() {
	*x = GetAvailableTablesRequest{}
	mi := &file_proto_table_table_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableTablesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableTablesRequest) ProtoMessage() {}

func (x *GetAvailableTablesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_table_table_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableTablesRequest.ProtoReflect.Descriptor instead.
func (*GetAvailableTablesRequest) Descriptor() ([]byte, []int) {
	return file_proto_table_table_proto_rawDescGZIP(), []int{13}
}

func (x *GetAvailableTablesRequest) GetMinCapacity() int32 {
	if x != nil {
		return x.MinCapacity
	}
	return 0
}

type GetAvailableTablesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tables        []*Table               `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableTablesResponse) Reset() {
	*x = GetAvailableTablesResponse{}
	mi := &file_proto_table_table_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableTablesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableTablesResponse) ProtoMessage() {}

func (x *GetAvailableTablesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_table_table_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableTablesResponse.ProtoReflect.Descriptor instead.
func (*GetAvailableTablesResponse) Descriptor() ([]byte, []int) {
	return file_proto_table_table_proto_rawDescGZIP(), []int{14}
}

func (x *GetAvailableTablesResponse) GetTables() []*Table {
	if x != nil {
		return x.Tables
	}
	return nil
}

func (x *GetAvailableTablesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetAvailableTablesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_table_table_proto protoreflect.FileDescriptor

const file_proto_table_table_proto_rawDesc = "" +
	"\n" +
	"\x17proto/table/table.proto\x12\x05table\x1a\x1fgoogle/protobuf/timestamp.proto\"\x83\x02\n" +
	"\x05Table\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\tR\atableId\x12!\n" +
	"\ftable_number\x18\x02 \x01(\x05R\vtableNumber\x12\x1a\n" +
	"\bcapacity\x18\x03 \x01(\x05R\bcapacity\x12*\n" +
	"\x06status\x18\x04 \x01(\x0e2\x12.table.TableStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"S\n" +
	"\x12CreateTableRequest\x12!\n" +
	"\ftable_number\x18\x01 \x01(\x05R\vtableNumber\x12\x1a\n" +
	"\bcapacity\x18\x02 \x01(\x05R\bcapacity\"m\n" +
	"\x13CreateTableResponse\x12\"\n" +
	"\x05table\x18\x01 \x01(\v2\f.table.TableR\x05table\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\",\n" +
	"\x0fGetTableRequest\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\tR\atableId\"j\n" +
	"\x10GetTableResponse\x12\"\n" +
	"\x05table\x18\x01 \x01(\v2\f.table.TableR\x05table\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"n\n" +
	"\x12UpdateTableRequest\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\tR\atableId\x12!\n" +
	"\ftable_number\x18\x02 \x01(\x05R\vtableNumber\x12\x1a\n" +
	"\bcapacity\x18\x03 \x01(\x05R\bcapacity\"m\n" +
	"\x13UpdateTableResponse\x12\"\n" +
	"\x05table\x18\x01 \x01(\v2\f.table.TableR\x05table\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"/\n" +
	"\x12DeleteTableRequest\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\tR\atableId\"I\n" +
	"\x13DeleteTableResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"p\n" +
	"\x11ListTablesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12*\n" +
	"\x06status\x18\x03 \x01(\x0e2\x12.table.TableStatusR\x06status\"\xb5\x01\n" +
	"\x12ListTablesResponse\x12$\n" +
	"\x06tables\x18\x01 \x03(\v2\f.table.TableR\x06tables\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"a\n" +
	"\x18UpdateTableStatusRequest\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\tR\atableId\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.table.TableStatusR\x06status\"s\n" +
	"\x19UpdateTableStatusResponse\x12\"\n" +
	"\x05table\x18\x01 \x01(\v2\f.table.TableR\x05table\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\">\n" +
	"\x19GetAvailableTablesRequest\x12!\n" +
	"\fmin_capacity\x18\x01 \x01(\x05R\vminCapacity\"v\n" +
	"\x1aGetAvailableTablesResponse\x12$\n" +
	"\x06tables\x18\x01 \x03(\v2\f.table.TableR\x06tables\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage*g\n" +
	"\vTableStatus\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10STATUS_AVAILABLE\x10\x01\x12\x13\n" +
	"\x0fSTATUS_CLEANING\x10\x02\x12\x19\n" +
	"\x15STATUS_OUT_OF_SERVICE\x10\x032\x93\x04\n" +
	"\fTableService\x12D\n" +
	"\vCreateTable\x12\x19.table.CreateTableRequest\x1a\x1a.table.CreateTableResponse\x12;\n" +
	"\bGetTable\x12\x16.table.GetTableRequest\x1a\x17.table.GetTableResponse\x12D\n" +
	"\vUpdateTable\x12\x19.table.UpdateTableRequest\x1a\x1a.table.UpdateTableResponse\x12D\n" +
	"\vDeleteTable\x12\x19.table.DeleteTableRequest\x1a\x1a.table.DeleteTableResponse\x12A\n" +
	"\n" +
	"ListTables\x12\x18.table.ListTablesRequest\x1a\x19.table.ListTablesResponse\x12V\n" +
	"\x11UpdateTableStatus\x12\x1f.table.UpdateTableStatusRequest\x1a .table.UpdateTableStatusResponse\x12Y\n" +
	"\x12GetAvailableTables\x12 .table.GetAvailableTablesRequest\x1a!.table.GetAvailableTablesResponseB#Z!restaurant-management/proto/tableb\x06proto3"

var (
	file_proto_table_table_proto_rawDescOnce sync.Once
	file_proto_table_table_proto_rawDescData []byte
)

func file_proto_table_table_proto_rawDescGZIP() []byte {
	file_proto_table_table_proto_rawDescOnce.Do(func() {
		file_proto_table_table_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_table_table_proto_rawDesc), len(file_proto_table_table_proto_rawDesc)))
	})
	return file_proto_table_table_proto_rawDescData
}

var file_proto_table_table_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_table_table_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_table_table_proto_goTypes = []any{
	(TableStatus)(0),                   // 0: table.TableStatus
	(*Table)(nil),                      // 1: table.Table
	(*CreateTableRequest)(nil),         // 2: table.CreateTableRequest
	(*CreateTableResponse)(nil),        // 3: table.CreateTableResponse
	(*GetTableRequest)(nil),            // 4: table.GetTableRequest
	(*GetTableResponse)(nil),           // 5: table.GetTableResponse
	(*UpdateTableRequest)(nil),         // 6: table.UpdateTableRequest
	(*UpdateTableResponse)(nil),        // 7: table.UpdateTableResponse
	(*DeleteTableRequest)(nil),         // 8: table.DeleteTableRequest
	(*DeleteTableResponse)(nil),        // 9: table.DeleteTableResponse
	(*ListTablesRequest)(nil),          // 10: table.ListTablesRequest
	(*ListTablesResponse)(nil),         // 11: table.ListTablesResponse
	(*UpdateTableStatusRequest)(nil),   // 12: table.UpdateTableStatusRequest
	(*UpdateTableStatusResponse)(nil),  // 13: table.UpdateTableStatusResponse
	(*GetAvailableTablesRequest)(nil),  // 14: table.GetAvailableTablesRequest
	(*GetAvailableTablesResponse)(nil), // 15: table.GetAvailableTablesResponse
	(*timestamppb.Timestamp)(nil),      // 16: google.protobuf.Timestamp
}
var file_proto_table_table_proto_depIdxs = []int32{
	0,  // 0: table.Table.status:type_name -> table.TableStatus
	16, // 1: table.Table.created_at:type_name -> google.protobuf.Timestamp
	16, // 2: table.Table.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 3: table.CreateTableResponse.table:type_name -> table.Table
	1,  // 4: table.GetTableResponse.table:type_name -> table.Table
	1,  // 5: table.UpdateTableResponse.table:type_name -> table.Table
	0,  // 6: table.ListTablesRequest.status:type_name -> table.TableStatus
	1,  // 7: table.ListTablesResponse.tables:type_name -> table.Table
	0,  // 8: table.UpdateTableStatusRequest.status:type_name -> table.TableStatus
	1,  // 9: table.UpdateTableStatusResponse.table:type_name -> table.Table
	1,  // 10: table.GetAvailableTablesResponse.tables:type_name -> table.Table
	2,  // 11: table.TableService.CreateTable:input_type -> table.CreateTableRequest
	4,  // 12: table.TableService.GetTable:input_type -> table.GetTableRequest
	6,  // 13: table.TableService.UpdateTable:input_type -> table.UpdateTableRequest
	8,  // 14: table.TableService.DeleteTable:input_type -> table.DeleteTableRequest
	10, // 15: table.TableService.ListTables:input_type -> table.ListTablesRequest
	12, // 16: table.TableService.UpdateTableStatus:input_type -> table.UpdateTableStatusRequest
	14, // 17: table.TableService.GetAvailableTables:input_type -> table.GetAvailableTablesRequest
	3,  // 18: table.TableService.CreateTable:output_type -> table.CreateTableResponse
	5,  // 19: table.TableService.GetTable:output_type -> table.GetTableResponse
	7,  // 20: table.TableService.UpdateTable:output_type -> table.UpdateTableResponse
	9,  // 21: table.TableService.DeleteTable:output_type -> table.DeleteTableResponse
	11, // 22: table.TableService.ListTables:output_type -> table.ListTablesResponse
	13, // 23: table.TableService.UpdateTableStatus:output_type -> table.UpdateTableStatusResponse
	15, // 24: table.TableService.GetAvailableTables:output_type -> table.GetAvailableTablesResponse
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_table_table_proto_init() }
func file_proto_table_table_proto_init() {
	if File_proto_table_table_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_table_table_proto_rawDesc), len(file_proto_table_table_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_table_table_proto_goTypes,
		DependencyIndexes: file_proto_table_table_proto_depIdxs,
		EnumInfos:         file_proto_table_table_proto_enumTypes,
		MessageInfos:      file_proto_table_table_proto_msgTypes,
	}.Build()
	File_proto_table_table_proto = out.File
	file_proto_table_table_proto_goTypes = nil
	file_proto_table_table_proto_depIdxs = nil
}
