// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/schedule/schedule.proto

package schedule

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Shift struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShiftId       string                 `protobuf:"bytes,1,opt,name=shift_id,json=shiftId,proto3" json:"shift_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`                            // YYYY-MM-DD
	StartTime     string                 `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // HH:MM
	EndTime       string                 `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // HH:MM
	Role          string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`                            // CHEF | WAITER | MANAGER
	Notes         string                 `protobuf:"bytes,7,opt,name=notes,proto3" json:"notes,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,8,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shift) Reset() {
	*x = Shift{}
	mi := &file_proto_schedule_schedule_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shift) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shift) ProtoMessage() {}

func (x *Shift) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_schedule_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shift.ProtoReflect.Descriptor instead.
func (*Shift) Descriptor() ([]byte, []int) {
	return file_proto_schedule_schedule_proto_rawDescGZIP(), []int{0}
}

func (x *Shift) GetShiftId() string {
	if x != nil {
		return x.ShiftId
	}
	return ""
}

func (x *Shift) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Shift) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Shift) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *Shift) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *Shift) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Shift) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *Shift) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Shift) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Shift) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ── CreateShift ───────────────────────────────────────────────
type CreateShiftRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	StartTime     string                 `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	Notes         string                 `protobuf:"bytes,6,opt,name=notes,proto3" json:"notes,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShiftRequest) Reset() {
	*x = CreateShiftRequest{}
	mi := &file_proto_schedule_schedule_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShiftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShiftRequest) ProtoMessage() {}

func (x *CreateShiftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_schedule_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShiftRequest.ProtoReflect.Descriptor instead.
func (*CreateShiftRequest) Descriptor() ([]byte, []int) {
	return file_proto_schedule_schedule_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShiftRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateShiftRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *CreateShiftRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *CreateShiftRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *CreateShiftRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CreateShiftRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *CreateShiftRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type CreateShiftResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shift         *Shift                 `protobuf:"bytes,1,opt,name=shift,proto3" json:"shift,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShiftResponse) Reset() {
	*x = CreateShiftResponse{}
	mi := &file_proto_schedule_schedule_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShiftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShiftResponse) ProtoMessage() {}

func (x *CreateShiftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_schedule_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShiftResponse.ProtoReflect.Descriptor instead.
func (*CreateShiftResponse) Descriptor() ([]byte, []int) {
	return file_proto_schedule_schedule_proto_rawDescGZIP(), []int{2}
}

func (x *CreateShiftResponse) GetShift() *Shift {
	if x != nil {
		return x.Shift
	}
	return nil
}

func (x *CreateShiftResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateShiftResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ── GetShift ──────────────────────────────────────────────────
type GetShiftRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShiftId       string                 `protobuf:"bytes,1,opt,name=shift_id,json=shiftId,proto3" json:"shift_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShiftRequest) Reset() {
	*x = GetShiftRequest{}
	mi := &file_proto_schedule_schedule_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShiftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShiftRequest) ProtoMessage() {}

func (x *GetShiftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_schedule_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShiftRequest.ProtoReflect.Descriptor instead.
func (*GetShiftRequest) Descriptor() ([]byte, []int) {
	return file_proto_schedule_schedule_proto_rawDescGZIP(), []int{3}
}

func (x *GetShiftRequest) GetShiftId() string {
	if x != nil {
		return x.ShiftId
	}
	return ""
}

type GetShiftResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shift         *Shift                 `protobuf:"bytes,1,opt,name=shift,proto3" json:"shift,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShiftResponse) Reset() {
	*x = GetShiftResponse{}
	mi := &file_proto_schedule_schedule_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShiftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShiftResponse) ProtoMessage() {}

func (x *GetShiftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_schedule_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShiftResponse.ProtoReflect.Descriptor instead.
func (*GetShiftResponse) Descriptor() ([]byte, []int) {
	return file_proto_schedule_schedule_proto_rawDescGZIP(), []int{4}
}

func (x *GetShiftResponse) GetShift() *Shift {
	if x != nil {
		return x.Shift
	}
	return nil
}

func (x *GetShiftResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetShiftResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ── UpdateShift ───────────────────────────────────────────────
type UpdateShiftRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShiftId       string                 `protobuf:"bytes,1,opt,name=shift_id,json=shiftId,proto3" json:"shift_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	StartTime     string                 `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Notes         string                 `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShiftRequest) Reset() {
	*x = UpdateShiftRequest{}
	mi := &file_proto_schedule_schedule_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShiftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShiftRequest) ProtoMessage() {}

func (x *UpdateShiftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_schedule_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShiftRequest.ProtoReflect.Descriptor instead.
func (*UpdateShiftRequest) Descriptor() ([]byte, []int) {
	return file_proto_schedule_schedule_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateShiftRequest) GetShiftId() string {
	if x != nil {
		return x.ShiftId
	}
	return ""
}

func (x *UpdateShiftRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *UpdateShiftRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *UpdateShiftRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *UpdateShiftRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type UpdateShiftResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shift         *Shift                 `protobuf:"bytes,1,opt,name=shift,proto3" json:"shift,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShiftResponse) Reset() {
	*x = UpdateShiftResponse{}
	mi := &file_proto_schedule_schedule_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShiftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShiftResponse) ProtoMessage() {}

func (x *UpdateShiftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_schedule_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShiftResponse.ProtoReflect.Descriptor instead.
func (*UpdateShiftResponse) Descriptor() ([]byte, []int) {
	return file_proto_schedule_schedule_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateShiftResponse) GetShift() *Shift {
	if x != nil {
		return x.Shift
	}
	return nil
}

func (x *UpdateShiftResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateShiftResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ── DeleteShift ───────────────────────────────────────────────
type DeleteShiftRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShiftId       string                 `protobuf:"bytes,1,opt,name=shift_id,json=shiftId,proto3" json:"shift_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShiftRequest) Reset() {
	*x = DeleteShiftRequest{}
	mi := &file_proto_schedule_schedule_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShiftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShiftRequest) ProtoMessage() {}

func (x *DeleteShiftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_schedule_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShiftRequest.ProtoReflect.Descriptor instead.
func (*DeleteShiftRequest) Descriptor() ([]byte, []int) {
	return file_proto_schedule_schedule_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteShiftRequest) GetShiftId() string {
	if x != nil {
		return x.ShiftId
	}
	return ""
}

type DeleteShiftResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShiftResponse) Reset() {
	*x = DeleteShiftResponse{}
	mi := &file_proto_schedule_schedule_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShiftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShiftResponse) ProtoMessage() {}

func (x *DeleteShiftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_schedule_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShiftResponse.ProtoReflect.Descriptor instead.
func (*DeleteShiftResponse) Descriptor() ([]byte, []int) {
	return file_proto_schedule_schedule_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteShiftResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteShiftResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ── ListShifts ────────────────────────────────────────────────
type ListShiftsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Month         string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`                 // "YYYY-MM" — filter by month
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // optional
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`                   // optional
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShiftsRequest) Reset() {
	*x = ListShiftsRequest{}
	mi := &file_proto_schedule_schedule_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShiftsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShiftsRequest) ProtoMessage() {}

func (x *ListShiftsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_schedule_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShiftsRequest.ProtoReflect.Descriptor instead.
func (*ListShiftsRequest) Descriptor() ([]byte, []int) {
	return file_proto_schedule_schedule_proto_rawDescGZIP(), []int{9}
}

func (x *ListShiftsRequest) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *ListShiftsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListShiftsRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ListShiftsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListShiftsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListShiftsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shifts        []*Shift               `protobuf:"bytes,1,rep,name=shifts,proto3" json:"shifts,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Success       bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShiftsResponse) Reset() {
	*x = ListShiftsResponse{}
	mi := &file_proto_schedule_schedule_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShiftsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShiftsResponse) ProtoMessage() {}

func (x *ListShiftsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_schedule_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShiftsResponse.ProtoReflect.Descriptor instead.
func (*ListShiftsResponse) Descriptor() ([]byte, []int) {
	return file_proto_schedule_schedule_proto_rawDescGZIP(), []int{10}
}

func (x *ListShiftsResponse) GetShifts() []*Shift {
	if x != nil {
		return x.Shifts
	}
	return nil
}

func (x *ListShiftsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListShiftsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListShiftsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListShiftsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListShiftsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_schedule_schedule_proto protoreflect.FileDescriptor

const file_proto_schedule_schedule_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/schedule/schedule.proto\x12\bschedule\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc8\x02\n" +
	"\x05Shift\x12\x19\n" +
	"\bshift_id\x18\x01 \x01(\tR\ashiftId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\tR\aendTime\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role\x12\x14\n" +
	"\x05notes\x18\a \x01(\tR\x05notes\x12\x1d\n" +
	"\n" +
	"created_by\x18\b \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc4\x01\n" +
	"\x12CreateShiftRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\tR\aendTime\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x14\n" +
	"\x05notes\x18\x06 \x01(\tR\x05notes\x12\x1d\n" +
	"\n" +
	"created_by\x18\a \x01(\tR\tcreatedBy\"p\n" +
	"\x13CreateShiftResponse\x12%\n" +
	"\x05shift\x18\x01 \x01(\v2\x0f.schedule.ShiftR\x05shift\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\",\n" +
	"\x0fGetShiftRequest\x12\x19\n" +
	"\bshift_id\x18\x01 \x01(\tR\ashiftId\"m\n" +
	"\x10GetShiftResponse\x12%\n" +
	"\x05shift\x18\x01 \x01(\v2\x0f.schedule.ShiftR\x05shift\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x93\x01\n" +
	"\x12UpdateShiftRequest\x12\x19\n" +
	"\bshift_id\x18\x01 \x01(\tR\ashiftId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\tR\aendTime\x12\x14\n" +
	"\x05notes\x18\x05 \x01(\tR\x05notes\"p\n" +
	"\x13UpdateShiftResponse\x12%\n" +
	"\x05shift\x18\x01 \x01(\v2\x0f.schedule.ShiftR\x05shift\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"/\n" +
	"\x12DeleteShiftRequest\x12\x19\n" +
	"\bshift_id\x18\x01 \x01(\tR\ashiftId\"I\n" +
	"\x13DeleteShiftResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x87\x01\n" +
	"\x11ListShiftsRequest\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"\xb8\x01\n" +
	"\x12ListShiftsResponse\x12'\n" +
	"\x06shifts\x18\x01 \x03(\v2\x0f.schedule.ShiftR\x06shifts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage2\x81\x03\n" +
	"\x0fScheduleService\x12J\n" +
	"\vCreateShift\x12\x1c.schedule.CreateShiftRequest\x1a\x1d.schedule.CreateShiftResponse\x12A\n" +
	"\bGetShift\x12\x19.schedule.GetShiftRequest\x1a\x1a.schedule.GetShiftResponse\x12J\n" +
	"\vUpdateShift\x12\x1c.schedule.UpdateShiftRequest\x1a\x1d.schedule.UpdateShiftResponse\x12J\n" +
	"\vDeleteShift\x12\x1c.schedule.DeleteShiftRequest\x1a\x1d.schedule.DeleteShiftResponse\x12G\n" +
	"\n" +
	"ListShifts\x12\x1b.schedule.ListShiftsRequest\x1a\x1c.schedule.ListShiftsResponseB&Z$restaurant-management/proto/scheduleb\x06proto3"

var (
	file_proto_schedule_schedule_proto_rawDescOnce sync.Once
	file_proto_schedule_schedule_proto_rawDescData []byte
)

func file_proto_schedule_schedule_proto_rawDescGZIP() []byte {
	file_proto_schedule_schedule_proto_rawDescOnce.Do(func() {
		file_proto_schedule_schedule_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_schedule_schedule_proto_rawDesc), len(file_proto_schedule_schedule_proto_rawDesc)))
	})
	return file_proto_schedule_schedule_proto_rawDescData
}

var file_proto_schedule_schedule_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_schedule_schedule_proto_goTypes = []any{
	(*Shift)(nil),                 // 0: schedule.Shift
	(*CreateShiftRequest)(nil),    // 1: schedule.CreateShiftRequest
	(*CreateShiftResponse)(nil),   // 2: schedule.CreateShiftResponse
	(*GetShiftRequest)(nil),       // 3: schedule.GetShiftRequest
	(*GetShiftResponse)(nil),      // 4: schedule.GetShiftResponse
	(*UpdateShiftRequest)(nil),    // 5: schedule.UpdateShiftRequest
	(*UpdateShiftResponse)(nil),   // 6: schedule.UpdateShiftResponse
	(*DeleteShiftRequest)(nil),    // 7: schedule.DeleteShiftRequest
	(*DeleteShiftResponse)(nil),   // 8: schedule.DeleteShiftResponse
	(*ListShiftsRequest)(nil),     // 9: schedule.ListShiftsRequest
	(*ListShiftsResponse)(nil),    // 10: schedule.ListShiftsResponse
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_proto_schedule_schedule_proto_depIdxs = []int32{
	11, // 0: schedule.Shift.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: schedule.Shift.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: schedule.CreateShiftResponse.shift:type_name -> schedule.Shift
	0,  // 3: schedule.GetShiftResponse.shift:type_name -> schedule.Shift
	0,  // 4: schedule.UpdateShiftResponse.shift:type_name -> schedule.Shift
	0,  // 5: schedule.ListShiftsResponse.shifts:type_name -> schedule.Shift
	1,  // 6: schedule.ScheduleService.CreateShift:input_type -> schedule.CreateShiftRequest
	3,  // 7: schedule.ScheduleService.GetShift:input_type -> schedule.GetShiftRequest
	5,  // 8: schedule.ScheduleService.UpdateShift:input_type -> schedule.UpdateShiftRequest
	7,  // 9: schedule.ScheduleService.DeleteShift:input_type -> schedule.DeleteShiftRequest
	9,  // 10: schedule.ScheduleService.ListShifts:input_type -> schedule.ListShiftsRequest
	2,  // 11: schedule.ScheduleService.CreateShift:output_type -> schedule.CreateShiftResponse
	4,  // 12: schedule.ScheduleService.GetShift:output_type -> schedule.GetShiftResponse
	6,  // 13: schedule.ScheduleService.UpdateShift:output_type -> schedule.UpdateShiftResponse
	8,  // 14: schedule.ScheduleService.DeleteShift:output_type -> schedule.DeleteShiftResponse
	10, // 15: schedule.ScheduleService.ListShifts:output_type -> schedule.ListShiftsResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_schedule_schedule_proto_init() }
func file_proto_schedule_schedule_proto_init() {
	if File_proto_schedule_schedule_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_schedule_schedule_proto_rawDesc), len(file_proto_schedule_schedule_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_schedule_schedule_proto_goTypes,
		DependencyIndexes: file_proto_schedule_schedule_proto_depIdxs,
		MessageInfos:      file_proto_schedule_schedule_proto_msgTypes,
	}.Build()
	File_proto_schedule_schedule_proto = out.File
	file_proto_schedule_schedule_proto_goTypes = nil
	file_proto_schedule_schedule_proto_depIdxs = nil
}
