// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: staff/staff.proto

package staff

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Staff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StaffId       string                 `protobuf:"bytes,1,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Contact       string                 `protobuf:"bytes,4,opt,name=contact,proto3" json:"contact,omitempty"`
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Staff) Reset() {
	*x = Staff{}
	mi := &file_staff_staff_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Staff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Staff) ProtoMessage() {}

func (x *Staff) ProtoReflect() protoreflect.Message {
	mi := &file_staff_staff_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Staff.ProtoReflect.Descriptor instead.
func (*Staff) Descriptor() ([]byte, []int) {
	return file_staff_staff_proto_rawDescGZIP(), []int{0}
}

func (x *Staff) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

func (x *Staff) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Staff) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Staff) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

func (x *Staff) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type CreateStaffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Contact       string                 `protobuf:"bytes,3,opt,name=contact,proto3" json:"contact,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStaffRequest) Reset() {
	*x = CreateStaffRequest{}
	mi := &file_staff_staff_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStaffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStaffRequest) ProtoMessage() {}

func (x *CreateStaffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_staff_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStaffRequest.ProtoReflect.Descriptor instead.
func (*CreateStaffRequest) Descriptor() ([]byte, []int) {
	return file_staff_staff_proto_rawDescGZIP(), []int{1}
}

func (x *CreateStaffRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateStaffRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CreateStaffRequest) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

func (x *CreateStaffRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type CreateStaffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Staff         *Staff                 `protobuf:"bytes,1,opt,name=staff,proto3" json:"staff,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStaffResponse) Reset() {
	*x = CreateStaffResponse{}
	mi := &file_staff_staff_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStaffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStaffResponse) ProtoMessage() {}

func (x *CreateStaffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staff_staff_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStaffResponse.ProtoReflect.Descriptor instead.
func (*CreateStaffResponse) Descriptor() ([]byte, []int) {
	return file_staff_staff_proto_rawDescGZIP(), []int{2}
}

func (x *CreateStaffResponse) GetStaff() *Staff {
	if x != nil {
		return x.Staff
	}
	return nil
}

func (x *CreateStaffResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateStaffResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetStaffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StaffId       string                 `protobuf:"bytes,1,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStaffRequest) Reset() {
	*x = GetStaffRequest{}
	mi := &file_staff_staff_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStaffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStaffRequest) ProtoMessage() {}

func (x *GetStaffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_staff_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStaffRequest.ProtoReflect.Descriptor instead.
func (*GetStaffRequest) Descriptor() ([]byte, []int) {
	return file_staff_staff_proto_rawDescGZIP(), []int{3}
}

func (x *GetStaffRequest) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

type GetStaffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Staff         *Staff                 `protobuf:"bytes,1,opt,name=staff,proto3" json:"staff,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStaffResponse) Reset() {
	*x = GetStaffResponse{}
	mi := &file_staff_staff_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStaffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStaffResponse) ProtoMessage() {}

func (x *GetStaffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staff_staff_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStaffResponse.ProtoReflect.Descriptor instead.
func (*GetStaffResponse) Descriptor() ([]byte, []int) {
	return file_staff_staff_proto_rawDescGZIP(), []int{4}
}

func (x *GetStaffResponse) GetStaff() *Staff {
	if x != nil {
		return x.Staff
	}
	return nil
}

func (x *GetStaffResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetStaffResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateStaffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StaffId       string                 `protobuf:"bytes,1,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Contact       string                 `protobuf:"bytes,4,opt,name=contact,proto3" json:"contact,omitempty"`
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStaffRequest) Reset() {
	*x = UpdateStaffRequest{}
	mi := &file_staff_staff_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStaffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStaffRequest) ProtoMessage() {}

func (x *UpdateStaffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_staff_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStaffRequest.ProtoReflect.Descriptor instead.
func (*UpdateStaffRequest) Descriptor() ([]byte, []int) {
	return file_staff_staff_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateStaffRequest) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

func (x *UpdateStaffRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateStaffRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UpdateStaffRequest) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

func (x *UpdateStaffRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type UpdateStaffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Staff         *Staff                 `protobuf:"bytes,1,opt,name=staff,proto3" json:"staff,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStaffResponse) Reset() {
	*x = UpdateStaffResponse{}
	mi := &file_staff_staff_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStaffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStaffResponse) ProtoMessage() {}

func (x *UpdateStaffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staff_staff_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStaffResponse.ProtoReflect.Descriptor instead.
func (*UpdateStaffResponse) Descriptor() ([]byte, []int) {
	return file_staff_staff_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateStaffResponse) GetStaff() *Staff {
	if x != nil {
		return x.Staff
	}
	return nil
}

func (x *UpdateStaffResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateStaffResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteStaffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StaffId       string                 `protobuf:"bytes,1,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStaffRequest) Reset() {
	*x = DeleteStaffRequest{}
	mi := &file_staff_staff_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStaffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStaffRequest) ProtoMessage() {}

func (x *DeleteStaffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_staff_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStaffRequest.ProtoReflect.Descriptor instead.
func (*DeleteStaffRequest) Descriptor() ([]byte, []int) {
	return file_staff_staff_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteStaffRequest) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

type DeleteStaffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStaffResponse) Reset() {
	*x = DeleteStaffResponse{}
	mi := &file_staff_staff_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStaffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStaffResponse) ProtoMessage() {}

func (x *DeleteStaffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staff_staff_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStaffResponse.ProtoReflect.Descriptor instead.
func (*DeleteStaffResponse) Descriptor() ([]byte, []int) {
	return file_staff_staff_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteStaffResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteStaffResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListStaffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Keyword       string                 `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStaffRequest) Reset() {
	*x = ListStaffRequest{}
	mi := &file_staff_staff_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStaffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStaffRequest) ProtoMessage() {}

func (x *ListStaffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_staff_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStaffRequest.ProtoReflect.Descriptor instead.
func (*ListStaffRequest) Descriptor() ([]byte, []int) {
	return file_staff_staff_proto_rawDescGZIP(), []int{9}
}

func (x *ListStaffRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListStaffRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListStaffRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type ListStaffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Staff         []*Staff               `protobuf:"bytes,1,rep,name=staff,proto3" json:"staff,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Success       bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStaffResponse) Reset() {
	*x = ListStaffResponse{}
	mi := &file_staff_staff_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStaffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStaffResponse) ProtoMessage() {}

func (x *ListStaffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staff_staff_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStaffResponse.ProtoReflect.Descriptor instead.
func (*ListStaffResponse) Descriptor() ([]byte, []int) {
	return file_staff_staff_proto_rawDescGZIP(), []int{10}
}

func (x *ListStaffResponse) GetStaff() []*Staff {
	if x != nil {
		return x.Staff
	}
	return nil
}

func (x *ListStaffResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListStaffResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListStaffResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListStaffResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListStaffResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_staff_staff_proto protoreflect.FileDescriptor

const file_staff_staff_proto_rawDesc = "" +
	"\n" +
	"\x11staff/staff.proto\x12\x05staff\"|\n" +
	"\x05Staff\x12\x19\n" +
	"\bstaff_id\x18\x01 \x01(\tR\astaffId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x18\n" +
	"\acontact\x18\x04 \x01(\tR\acontact\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\"n\n" +
	"\x12CreateStaffRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x18\n" +
	"\acontact\x18\x03 \x01(\tR\acontact\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\"m\n" +
	"\x13CreateStaffResponse\x12\"\n" +
	"\x05staff\x18\x01 \x01(\v2\f.staff.StaffR\x05staff\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\",\n" +
	"\x0fGetStaffRequest\x12\x19\n" +
	"\bstaff_id\x18\x01 \x01(\tR\astaffId\"j\n" +
	"\x10GetStaffResponse\x12\"\n" +
	"\x05staff\x18\x01 \x01(\v2\f.staff.StaffR\x05staff\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x89\x01\n" +
	"\x12UpdateStaffRequest\x12\x19\n" +
	"\bstaff_id\x18\x01 \x01(\tR\astaffId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x18\n" +
	"\acontact\x18\x04 \x01(\tR\acontact\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\"m\n" +
	"\x13UpdateStaffResponse\x12\"\n" +
	"\x05staff\x18\x01 \x01(\v2\f.staff.StaffR\x05staff\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"/\n" +
	"\x12DeleteStaffRequest\x12\x19\n" +
	"\bstaff_id\x18\x01 \x01(\tR\astaffId\"I\n" +
	"\x13DeleteStaffResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"]\n" +
	"\x10ListStaffRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\"\xb2\x01\n" +
	"\x11ListStaffResponse\x12\"\n" +
	"\x05staff\x18\x01 \x03(\v2\f.staff.StaffR\x05staff\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage2\xdd\x02\n" +
	"\fStaffService\x12D\n" +
	"\vCreateStaff\x12\x19.staff.CreateStaffRequest\x1a\x1a.staff.CreateStaffResponse\x12;\n" +
	"\bGetStaff\x12\x16.staff.GetStaffRequest\x1a\x17.staff.GetStaffResponse\x12D\n" +
	"\vUpdateStaff\x12\x19.staff.UpdateStaffRequest\x1a\x1a.staff.UpdateStaffResponse\x12D\n" +
	"\vDeleteStaff\x12\x19.staff.DeleteStaffRequest\x1a\x1a.staff.DeleteStaffResponse\x12>\n" +
	"\tListStaff\x12\x17.staff.ListStaffRequest\x1a\x18.staff.ListStaffResponseB#Z!restaurant-management/proto/staffb\x06proto3"

var (
	file_staff_staff_proto_rawDescOnce sync.Once
	file_staff_staff_proto_rawDescData []byte
)

func file_staff_staff_proto_rawDescGZIP() []byte {
	file_staff_staff_proto_rawDescOnce.Do(func() {
		file_staff_staff_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_staff_staff_proto_rawDesc), len(file_staff_staff_proto_rawDesc)))
	})
	return file_staff_staff_proto_rawDescData
}

var file_staff_staff_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_staff_staff_proto_goTypes = []any{
	(*Staff)(nil),               // 0: staff.Staff
	(*CreateStaffRequest)(nil),  // 1: staff.CreateStaffRequest
	(*CreateStaffResponse)(nil), // 2: staff.CreateStaffResponse
	(*GetStaffRequest)(nil),     // 3: staff.GetStaffRequest
	(*GetStaffResponse)(nil),    // 4: staff.GetStaffResponse
	(*UpdateStaffRequest)(nil),  // 5: staff.UpdateStaffRequest
	(*UpdateStaffResponse)(nil), // 6: staff.UpdateStaffResponse
	(*DeleteStaffRequest)(nil),  // 7: staff.DeleteStaffRequest
	(*DeleteStaffResponse)(nil), // 8: staff.DeleteStaffResponse
	(*ListStaffRequest)(nil),    // 9: staff.ListStaffRequest
	(*ListStaffResponse)(nil),   // 10: staff.ListStaffResponse
}
var file_staff_staff_proto_depIdxs = []int32{
	0,  // 0: staff.CreateStaffResponse.staff:type_name -> staff.Staff
	0,  // 1: staff.GetStaffResponse.staff:type_name -> staff.Staff
	0,  // 2: staff.UpdateStaffResponse.staff:type_name -> staff.Staff
	0,  // 3: staff.ListStaffResponse.staff:type_name -> staff.Staff
	1,  // 4: staff.StaffService.CreateStaff:input_type -> staff.CreateStaffRequest
	3,  // 5: staff.StaffService.GetStaff:input_type -> staff.GetStaffRequest
	5,  // 6: staff.StaffService.UpdateStaff:input_type -> staff.UpdateStaffRequest
	7,  // 7: staff.StaffService.DeleteStaff:input_type -> staff.DeleteStaffRequest
	9,  // 8: staff.StaffService.ListStaff:input_type -> staff.ListStaffRequest
	2,  // 9: staff.StaffService.CreateStaff:output_type -> staff.CreateStaffResponse
	4,  // 10: staff.StaffService.GetStaff:output_type -> staff.GetStaffResponse
	6,  // 11: staff.StaffService.UpdateStaff:output_type -> staff.UpdateStaffResponse
	8,  // 12: staff.StaffService.DeleteStaff:output_type -> staff.DeleteStaffResponse
	10, // 13: staff.StaffService.ListStaff:output_type -> staff.ListStaffResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_staff_staff_proto_init() }
func file_staff_staff_proto_init() {
	if File_staff_staff_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_staff_staff_proto_rawDesc), len(file_staff_staff_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_staff_staff_proto_goTypes,
		DependencyIndexes: file_staff_staff_proto_depIdxs,
		MessageInfos:      file_staff_staff_proto_msgTypes,
	}.Build()
	File_staff_staff_proto = out.File
	file_staff_staff_proto_goTypes = nil
	file_staff_staff_proto_depIdxs = nil
}
