// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.9
// source: report/report.proto

package report

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReportService_GetSalesReport_FullMethodName            = "/report.ReportService/GetSalesReport"
	ReportService_GetInventoryReport_FullMethodName        = "/report.ReportService/GetInventoryReport"
	ReportService_GetOrderReport_FullMethodName            = "/report.ReportService/GetOrderReport"
	ReportService_GetStaffPerformanceReport_FullMethodName = "/report.ReportService/GetStaffPerformanceReport"
	ReportService_GetPopularItemsReport_FullMethodName     = "/report.ReportService/GetPopularItemsReport"
	ReportService_GetRevenueAnalytics_FullMethodName       = "/report.ReportService/GetRevenueAnalytics"
	ReportService_ExportReport_FullMethodName              = "/report.ReportService/ExportReport"
)

// ReportServiceClient is the client API for ReportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Report Service Definition
type ReportServiceClient interface {
	GetSalesReport(ctx context.Context, in *GetSalesReportRequest, opts ...grpc.CallOption) (*GetSalesReportResponse, error)
	GetInventoryReport(ctx context.Context, in *GetInventoryReportRequest, opts ...grpc.CallOption) (*GetInventoryReportResponse, error)
	GetOrderReport(ctx context.Context, in *GetOrderReportRequest, opts ...grpc.CallOption) (*GetOrderReportResponse, error)
	GetStaffPerformanceReport(ctx context.Context, in *GetStaffPerformanceReportRequest, opts ...grpc.CallOption) (*GetStaffPerformanceReportResponse, error)
	GetPopularItemsReport(ctx context.Context, in *GetPopularItemsReportRequest, opts ...grpc.CallOption) (*GetPopularItemsReportResponse, error)
	GetRevenueAnalytics(ctx context.Context, in *GetRevenueAnalyticsRequest, opts ...grpc.CallOption) (*GetRevenueAnalyticsResponse, error)
	ExportReport(ctx context.Context, in *ExportReportRequest, opts ...grpc.CallOption) (*ExportReportResponse, error)
}

type reportServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReportServiceClient(cc grpc.ClientConnInterface) ReportServiceClient {
	return &reportServiceClient{cc}
}

func (c *reportServiceClient) GetSalesReport(ctx context.Context, in *GetSalesReportRequest, opts ...grpc.CallOption) (*GetSalesReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSalesReportResponse)
	err := c.cc.Invoke(ctx, ReportService_GetSalesReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportServiceClient) GetInventoryReport(ctx context.Context, in *GetInventoryReportRequest, opts ...grpc.CallOption) (*GetInventoryReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInventoryReportResponse)
	err := c.cc.Invoke(ctx, ReportService_GetInventoryReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportServiceClient) GetOrderReport(ctx context.Context, in *GetOrderReportRequest, opts ...grpc.CallOption) (*GetOrderReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderReportResponse)
	err := c.cc.Invoke(ctx, ReportService_GetOrderReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportServiceClient) GetStaffPerformanceReport(ctx context.Context, in *GetStaffPerformanceReportRequest, opts ...grpc.CallOption) (*GetStaffPerformanceReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStaffPerformanceReportResponse)
	err := c.cc.Invoke(ctx, ReportService_GetStaffPerformanceReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportServiceClient) GetPopularItemsReport(ctx context.Context, in *GetPopularItemsReportRequest, opts ...grpc.CallOption) (*GetPopularItemsReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPopularItemsReportResponse)
	err := c.cc.Invoke(ctx, ReportService_GetPopularItemsReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportServiceClient) GetRevenueAnalytics(ctx context.Context, in *GetRevenueAnalyticsRequest, opts ...grpc.CallOption) (*GetRevenueAnalyticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRevenueAnalyticsResponse)
	err := c.cc.Invoke(ctx, ReportService_GetRevenueAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportServiceClient) ExportReport(ctx context.Context, in *ExportReportRequest, opts ...grpc.CallOption) (*ExportReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportReportResponse)
	err := c.cc.Invoke(ctx, ReportService_ExportReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReportServiceServer is the server API for ReportService service.
// All implementations must embed UnimplementedReportServiceServer
// for forward compatibility.
//
// Report Service Definition
type ReportServiceServer interface {
	GetSalesReport(context.Context, *GetSalesReportRequest) (*GetSalesReportResponse, error)
	GetInventoryReport(context.Context, *GetInventoryReportRequest) (*GetInventoryReportResponse, error)
	GetOrderReport(context.Context, *GetOrderReportRequest) (*GetOrderReportResponse, error)
	GetStaffPerformanceReport(context.Context, *GetStaffPerformanceReportRequest) (*GetStaffPerformanceReportResponse, error)
	GetPopularItemsReport(context.Context, *GetPopularItemsReportRequest) (*GetPopularItemsReportResponse, error)
	GetRevenueAnalytics(context.Context, *GetRevenueAnalyticsRequest) (*GetRevenueAnalyticsResponse, error)
	ExportReport(context.Context, *ExportReportRequest) (*ExportReportResponse, error)
	mustEmbedUnimplementedReportServiceServer()
}

// UnimplementedReportServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReportServiceServer struct{}

func (UnimplementedReportServiceServer) GetSalesReport(context.Context, *GetSalesReportRequest) (*GetSalesReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSalesReport not implemented")
}
func (UnimplementedReportServiceServer) GetInventoryReport(context.Context, *GetInventoryReportRequest) (*GetInventoryReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInventoryReport not implemented")
}
func (UnimplementedReportServiceServer) GetOrderReport(context.Context, *GetOrderReportRequest) (*GetOrderReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrderReport not implemented")
}
func (UnimplementedReportServiceServer) GetStaffPerformanceReport(context.Context, *GetStaffPerformanceReportRequest) (*GetStaffPerformanceReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStaffPerformanceReport not implemented")
}
func (UnimplementedReportServiceServer) GetPopularItemsReport(context.Context, *GetPopularItemsReportRequest) (*GetPopularItemsReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPopularItemsReport not implemented")
}
func (UnimplementedReportServiceServer) GetRevenueAnalytics(context.Context, *GetRevenueAnalyticsRequest) (*GetRevenueAnalyticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRevenueAnalytics not implemented")
}
func (UnimplementedReportServiceServer) ExportReport(context.Context, *ExportReportRequest) (*ExportReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportReport not implemented")
}
func (UnimplementedReportServiceServer) mustEmbedUnimplementedReportServiceServer() {}
func (UnimplementedReportServiceServer) testEmbeddedByValue()                       {}

// UnsafeReportServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReportServiceServer will
// result in compilation errors.
type UnsafeReportServiceServer interface {
	mustEmbedUnimplementedReportServiceServer()
}

func RegisterReportServiceServer(s grpc.ServiceRegistrar, srv ReportServiceServer) {
	// If the following call panics, it indicates UnimplementedReportServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReportService_ServiceDesc, srv)
}

func _ReportService_GetSalesReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSalesReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).GetSalesReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportService_GetSalesReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).GetSalesReport(ctx, req.(*GetSalesReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportService_GetInventoryReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInventoryReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).GetInventoryReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportService_GetInventoryReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).GetInventoryReport(ctx, req.(*GetInventoryReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportService_GetOrderReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).GetOrderReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportService_GetOrderReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).GetOrderReport(ctx, req.(*GetOrderReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportService_GetStaffPerformanceReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStaffPerformanceReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).GetStaffPerformanceReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportService_GetStaffPerformanceReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).GetStaffPerformanceReport(ctx, req.(*GetStaffPerformanceReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportService_GetPopularItemsReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPopularItemsReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).GetPopularItemsReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportService_GetPopularItemsReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).GetPopularItemsReport(ctx, req.(*GetPopularItemsReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportService_GetRevenueAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRevenueAnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).GetRevenueAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportService_GetRevenueAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).GetRevenueAnalytics(ctx, req.(*GetRevenueAnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportService_ExportReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).ExportReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportService_ExportReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).ExportReport(ctx, req.(*ExportReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReportService_ServiceDesc is the grpc.ServiceDesc for ReportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "report.ReportService",
	HandlerType: (*ReportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSalesReport",
			Handler:    _ReportService_GetSalesReport_Handler,
		},
		{
			MethodName: "GetInventoryReport",
			Handler:    _ReportService_GetInventoryReport_Handler,
		},
		{
			MethodName: "GetOrderReport",
			Handler:    _ReportService_GetOrderReport_Handler,
		},
		{
			MethodName: "GetStaffPerformanceReport",
			Handler:    _ReportService_GetStaffPerformanceReport_Handler,
		},
		{
			MethodName: "GetPopularItemsReport",
			Handler:    _ReportService_GetPopularItemsReport_Handler,
		},
		{
			MethodName: "GetRevenueAnalytics",
			Handler:    _ReportService_GetRevenueAnalytics_Handler,
		},
		{
			MethodName: "ExportReport",
			Handler:    _ReportService_ExportReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "report/report.proto",
}
