// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: report/report.proto

package report

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enums
type ReportPeriod int32

const (
	ReportPeriod_PERIOD_UNKNOWN ReportPeriod = 0
	ReportPeriod_PERIOD_DAILY   ReportPeriod = 1
	ReportPeriod_PERIOD_WEEKLY  ReportPeriod = 2
	ReportPeriod_PERIOD_MONTHLY ReportPeriod = 3
	ReportPeriod_PERIOD_YEARLY  ReportPeriod = 4
	ReportPeriod_PERIOD_CUSTOM  ReportPeriod = 5
)

// Enum value maps for ReportPeriod.
var (
	ReportPeriod_name = map[int32]string{
		0: "PERIOD_UNKNOWN",
		1: "PERIOD_DAILY",
		2: "PERIOD_WEEKLY",
		3: "PERIOD_MONTHLY",
		4: "PERIOD_YEARLY",
		5: "PERIOD_CUSTOM",
	}
	ReportPeriod_value = map[string]int32{
		"PERIOD_UNKNOWN": 0,
		"PERIOD_DAILY":   1,
		"PERIOD_WEEKLY":  2,
		"PERIOD_MONTHLY": 3,
		"PERIOD_YEARLY":  4,
		"PERIOD_CUSTOM":  5,
	}
)

func (x ReportPeriod) Enum() *ReportPeriod {
	p := new(ReportPeriod)
	*p = x
	return p
}

func (x ReportPeriod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReportPeriod) Descriptor() protoreflect.EnumDescriptor {
	return file_report_report_proto_enumTypes[0].Descriptor()
}

func (ReportPeriod) Type() protoreflect.EnumType {
	return &file_report_report_proto_enumTypes[0]
}

func (x ReportPeriod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReportPeriod.Descriptor instead.
func (ReportPeriod) EnumDescriptor() ([]byte, []int) {
	return file_report_report_proto_rawDescGZIP(), []int{0}
}

type ExportFormat int32

const (
	ExportFormat_FORMAT_UNKNOWN ExportFormat = 0
	ExportFormat_FORMAT_PDF     ExportFormat = 1
	ExportFormat_FORMAT_EXCEL   ExportFormat = 2
	ExportFormat_FORMAT_CSV     ExportFormat = 3
	ExportFormat_FORMAT_JSON    ExportFormat = 4
)

// Enum value maps for ExportFormat.
var (
	ExportFormat_name = map[int32]string{
		0: "FORMAT_UNKNOWN",
		1: "FORMAT_PDF",
		2: "FORMAT_EXCEL",
		3: "FORMAT_CSV",
		4: "FORMAT_JSON",
	}
	ExportFormat_value = map[string]int32{
		"FORMAT_UNKNOWN": 0,
		"FORMAT_PDF":     1,
		"FORMAT_EXCEL":   2,
		"FORMAT_CSV":     3,
		"FORMAT_JSON":    4,
	}
)

func (x ExportFormat) Enum() *ExportFormat {
	p := new(ExportFormat)
	*p = x
	return p
}

func (x ExportFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExportFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_report_report_proto_enumTypes[1].Descriptor()
}

func (ExportFormat) Type() protoreflect.EnumType {
	return &file_report_report_proto_enumTypes[1]
}

func (x ExportFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExportFormat.Descriptor instead.
func (ExportFormat) EnumDescriptor() ([]byte, []int) {
	return file_report_report_proto_rawDescGZIP(), []int{1}
}

// Messages
type SalesReport struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalSales        float64                `protobuf:"fixed64,1,opt,name=total_sales,json=totalSales,proto3" json:"total_sales,omitempty"`
	TotalTax          float64                `protobuf:"fixed64,2,opt,name=total_tax,json=totalTax,proto3" json:"total_tax,omitempty"`
	TotalDiscount     float64                `protobuf:"fixed64,3,opt,name=total_discount,json=totalDiscount,proto3" json:"total_discount,omitempty"`
	NetRevenue        float64                `protobuf:"fixed64,4,opt,name=net_revenue,json=netRevenue,proto3" json:"net_revenue,omitempty"`
	TotalOrders       int32                  `protobuf:"varint,5,opt,name=total_orders,json=totalOrders,proto3" json:"total_orders,omitempty"`
	AverageOrderValue float64                `protobuf:"fixed64,6,opt,name=average_order_value,json=averageOrderValue,proto3" json:"average_order_value,omitempty"`
	DailyBreakdown    []*DailySales          `protobuf:"bytes,7,rep,name=daily_breakdown,json=dailyBreakdown,proto3" json:"daily_breakdown,omitempty"`
	PaymentBreakdown  []*PaymentMethodSales  `protobuf:"bytes,8,rep,name=payment_breakdown,json=paymentBreakdown,proto3" json:"payment_breakdown,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SalesReport) Reset() {
	*x = SalesReport{}
	mi := &file_report_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SalesReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SalesReport) ProtoMessage() {}

func (x *SalesReport) ProtoReflect() protoreflect.Message {
	mi := &file_report_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SalesReport.ProtoReflect.Descriptor instead.
func (*SalesReport) Descriptor() ([]byte, []int) {
	return file_report_report_proto_rawDescGZIP(), []int{0}
}

func (x *SalesReport) GetTotalSales() float64 {
	if x != nil {
		return x.TotalSales
	}
	return 0
}

func (x *SalesReport) GetTotalTax() float64 {
	if x != nil {
		return x.TotalTax
	}
	return 0
}

func (x *SalesReport) GetTotalDiscount() float64 {
	if x != nil {
		return x.TotalDiscount
	}
	return 0
}

func (x *SalesReport) GetNetRevenue() float64 {
	if x != nil {
		return x.NetRevenue
	}
	return 0
}

func (x *SalesReport) GetTotalOrders() int32 {
	if x != nil {
		return x.TotalOrders
	}
	return 0
}

func (x *SalesReport) GetAverageOrderValue() float64 {
	if x != nil {
		return x.AverageOrderValue
	}
	return 0
}

func (x *SalesReport) GetDailyBreakdown() []*DailySales {
	if x != nil {
		return x.DailyBreakdown
	}
	return nil
}

func (x *SalesReport) GetPaymentBreakdown() []*PaymentMethodSales {
	if x != nil {
		return x.PaymentBreakdown
	}
	return nil
}

type DailySales struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Sales         float64                `protobuf:"fixed64,2,opt,name=sales,proto3" json:"sales,omitempty"`
	Orders        int32                  `protobuf:"varint,3,opt,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailySales) Reset() {
	*x = DailySales{}
	mi := &file_report_report_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailySales) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailySales) ProtoMessage() {}

func (x *DailySales) ProtoReflect() protoreflect.Message {
	mi := &file_report_report_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailySales.ProtoReflect.Descriptor instead.
func (*DailySales) Descriptor() ([]byte, []int) {
	return file_report_report_proto_rawDescGZIP(), []int{1}
}

func (x *DailySales) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailySales) GetSales() float64 {
	if x != nil {
		return x.Sales
	}
	return 0
}

func (x *DailySales) GetOrders() int32 {
	if x != nil {
		return x.Orders
	}
	return 0
}

type PaymentMethodSales struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentMethodSales) Reset() {
	*x = PaymentMethodSales{}
	mi := &file_report_report_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentMethodSales) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentMethodSales) ProtoMessage() {}

func (x *PaymentMethodSales) ProtoReflect() protoreflect.Message {
	mi := &file_report_report_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentMethodSales.ProtoReflect.Descriptor instead.
func (*PaymentMethodSales) Descriptor() ([]byte, []int) {
	return file_report_report_proto_rawDescGZIP(), []int{2}
}

func (x *PaymentMethodSales) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *PaymentMethodSales) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentMethodSales) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type InventoryReport struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TotalInventoryValue float64                `protobuf:"fixed64,1,opt,name=total_inventory_value,json=totalInventoryValue,proto3" json:"total_inventory_value,omitempty"`
	LowStockItemsCount  int32                  `protobuf:"varint,2,opt,name=low_stock_items_count,json=lowStockItemsCount,proto3" json:"low_stock_items_count,omitempty"`
	Items               []*IngredientStock     `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	TotalWasteValue     float64                `protobuf:"fixed64,4,opt,name=total_waste_value,json=totalWasteValue,proto3" json:"total_waste_value,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *InventoryReport) Reset() {
	*x = InventoryReport{}
	mi := &file_report_report_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryReport) ProtoMessage() {}

func (x *InventoryReport) ProtoReflect() protoreflect.Message {
	mi := &file_report_report_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryReport.ProtoReflect.Descriptor instead.
func (*InventoryReport) Descriptor() ([]byte, []int) {
	return file_report_report_proto_rawDescGZIP(), []int{3}
}

func (x *InventoryReport) GetTotalInventoryValue() float64 {
	if x != nil {
		return x.TotalInventoryValue
	}
	return 0
}

func (x *InventoryReport) GetLowStockItemsCount() int32 {
	if x != nil {
		return x.LowStockItemsCount
	}
	return 0
}

func (x *InventoryReport) GetItems() []*IngredientStock {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *InventoryReport) GetTotalWasteValue() float64 {
	if x != nil {
		return x.TotalWasteValue
	}
	return 0
}

type IngredientStock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IngredientId  string                 `protobuf:"bytes,1,opt,name=ingredient_id,json=ingredientId,proto3" json:"ingredient_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CurrentStock  float64                `protobuf:"fixed64,3,opt,name=current_stock,json=currentStock,proto3" json:"current_stock,omitempty"`
	MinimumStock  float64                `protobuf:"fixed64,4,opt,name=minimum_stock,json=minimumStock,proto3" json:"minimum_stock,omitempty"`
	UnitCost      float64                `protobuf:"fixed64,5,opt,name=unit_cost,json=unitCost,proto3" json:"unit_cost,omitempty"`
	TotalValue    float64                `protobuf:"fixed64,6,opt,name=total_value,json=totalValue,proto3" json:"total_value,omitempty"`
	IsLowStock    bool                   `protobuf:"varint,7,opt,name=is_low_stock,json=isLowStock,proto3" json:"is_low_stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngredientStock) Reset() {
	*x = IngredientStock{}
	mi := &file_report_report_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngredientStock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngredientStock) ProtoMessage() {}

func (x *IngredientStock) ProtoReflect() protoreflect.Message {
	mi := &file_report_report_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngredientStock.ProtoReflect.Descriptor instead.
func (*IngredientStock) Descriptor() ([]byte, []int) {
	return file_report_report_proto_rawDescGZIP(), []int{4}
}

func (x *IngredientStock) GetIngredientId() string {
	if x != nil {
		return x.IngredientId
	}
	return ""
}

func (x *IngredientStock) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IngredientStock) GetCurrentStock() float64 {
	if x != nil {
		return x.CurrentStock
	}
	return 0
}

func (x *IngredientStock) GetMinimumStock() float64 {
	if x != nil {
		return x.MinimumStock
	}
	return 0
}

func (x *IngredientStock) GetUnitCost() float64 {
	if x != nil {
		return x.UnitCost
	}
	return 0
}

func (x *IngredientStock) GetTotalValue() float64 {
	if x != nil {
		return x.TotalValue
	}
	return 0
}

func (x *IngredientStock) GetIsLowStock() bool {
	if x != nil {
		return x.IsLowStock
	}
	return false
}

type OrderReport struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TotalOrders            int32                  `protobuf:"varint,1,opt,name=total_orders,json=totalOrders,proto3" json:"total_orders,omitempty"`
	CompletedOrders        int32                  `protobuf:"varint,2,opt,name=completed_orders,json=completedOrders,proto3" json:"completed_orders,omitempty"`
	CancelledOrders        int32                  `protobuf:"varint,3,opt,name=cancelled_orders,json=cancelledOrders,proto3" json:"cancelled_orders,omitempty"`
	CompletionRate         float64                `protobuf:"fixed64,4,opt,name=completion_rate,json=completionRate,proto3" json:"completion_rate,omitempty"`
	AveragePreparationTime float64                `protobuf:"fixed64,5,opt,name=average_preparation_time,json=averagePreparationTime,proto3" json:"average_preparation_time,omitempty"`
	HourlyBreakdown        []*HourlyOrders        `protobuf:"bytes,6,rep,name=hourly_breakdown,json=hourlyBreakdown,proto3" json:"hourly_breakdown,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *OrderReport) Reset() {
	*x = OrderReport{}
	mi := &file_report_report_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderReport) ProtoMessage() {}

func (x *OrderReport) ProtoReflect() protoreflect.Message {
	mi := &file_report_report_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderReport.ProtoReflect.Descriptor instead.
func (*OrderReport) Descriptor() ([]byte, []int) {
	return file_report_report_proto_rawDescGZIP(), []int{5}
}

func (x *OrderReport) GetTotalOrders() int32 {
	if x != nil {
		return x.TotalOrders
	}
	return 0
}

func (x *OrderReport) GetCompletedOrders() int32 {
	if x != nil {
		return x.CompletedOrders
	}
	return 0
}

func (x *OrderReport) GetCancelledOrders() int32 {
	if x != nil {
		return x.CancelledOrders
	}
	return 0
}

func (x *OrderReport) GetCompletionRate() float64 {
	if x != nil {
		return x.CompletionRate
	}
	return 0
}

func (x *OrderReport) GetAveragePreparationTime() float64 {
	if x != nil {
		return x.AveragePreparationTime
	}
	return 0
}

func (x *OrderReport) GetHourlyBreakdown() []*HourlyOrders {
	if x != nil {
		return x.HourlyBreakdown
	}
	return nil
}

type HourlyOrders struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hour          int32                  `protobuf:"varint,1,opt,name=hour,proto3" json:"hour,omitempty"`
	OrderCount    int32                  `protobuf:"varint,2,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HourlyOrders) Reset() {
	*x = HourlyOrders{}
	mi := &file_report_report_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HourlyOrders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HourlyOrders) ProtoMessage() {}

func (x *HourlyOrders) ProtoReflect() protoreflect.Message {
	mi := &file_report_report_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HourlyOrders.ProtoReflect.Descriptor instead.
func (*HourlyOrders) Descriptor() ([]byte, []int) {
	return file_report_report_proto_rawDescGZIP(), []int{6}
}

func (x *HourlyOrders) GetHour() int32 {
	if x != nil {
		return x.Hour
	}
	return 0
}

func (x *HourlyOrders) GetOrderCount() int32 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

type StaffPerformance struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	StaffId            string                 `protobuf:"bytes,1,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	StaffName          string                 `protobuf:"bytes,2,opt,name=staff_name,json=staffName,proto3" json:"staff_name,omitempty"`
	OrdersHandled      int32                  `protobuf:"varint,3,opt,name=orders_handled,json=ordersHandled,proto3" json:"orders_handled,omitempty"`
	TotalSales         float64                `protobuf:"fixed64,4,opt,name=total_sales,json=totalSales,proto3" json:"total_sales,omitempty"`
	AverageOrderValue  float64                `protobuf:"fixed64,5,opt,name=average_order_value,json=averageOrderValue,proto3" json:"average_order_value,omitempty"`
	CustomerComplaints int32                  `protobuf:"varint,6,opt,name=customer_complaints,json=customerComplaints,proto3" json:"customer_complaints,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StaffPerformance) Reset() {
	*x = StaffPerformance{}
	mi := &file_report_report_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaffPerformance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffPerformance) ProtoMessage() {}

func (x *StaffPerformance) ProtoReflect() protoreflect.Message {
	mi := &file_report_report_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffPerformance.ProtoReflect.Descriptor instead.
func (*StaffPerformance) Descriptor() ([]byte, []int) {
	return file_report_report_proto_rawDescGZIP(), []int{7}
}

func (x *StaffPerformance) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

func (x *StaffPerformance) GetStaffName() string {
	if x != nil {
		return x.StaffName
	}
	return ""
}

func (x *StaffPerformance) GetOrdersHandled() int32 {
	if x != nil {
		return x.OrdersHandled
	}
	return 0
}

func (x *StaffPerformance) GetTotalSales() float64 {
	if x != nil {
		return x.TotalSales
	}
	return 0
}

func (x *StaffPerformance) GetAverageOrderValue() float64 {
	if x != nil {
		return x.AverageOrderValue
	}
	return 0
}

func (x *StaffPerformance) GetCustomerComplaints() int32 {
	if x != nil {
		return x.CustomerComplaints
	}
	return 0
}

type PopularItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemName      string                 `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	QuantitySold  int32                  `protobuf:"varint,3,opt,name=quantity_sold,json=quantitySold,proto3" json:"quantity_sold,omitempty"`
	Revenue       float64                `protobuf:"fixed64,4,opt,name=revenue,proto3" json:"revenue,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PopularItem) Reset() {
	*x = PopularItem{}
	mi := &file_report_report_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PopularItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopularItem) ProtoMessage() {}

func (x *PopularItem) ProtoReflect() protoreflect.Message {
	mi := &file_report_report_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopularItem.ProtoReflect.Descriptor instead.
func (*PopularItem) Descriptor() ([]byte, []int) {
	return file_report_report_proto_rawDescGZIP(), []int{8}
}

func (x *PopularItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *PopularItem) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *PopularItem) GetQuantitySold() int32 {
	if x != nil {
		return x.QuantitySold
	}
	return 0
}

func (x *PopularItem) GetRevenue() float64 {
	if x != nil {
		return x.Revenue
	}
	return 0
}

func (x *PopularItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type RevenueAnalytics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalRevenue  float64                `protobuf:"fixed64,1,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	GrowthRate    float64                `protobuf:"fixed64,2,opt,name=growth_rate,json=growthRate,proto3" json:"growth_rate,omitempty"`
	TrendData     []*DailySales          `protobuf:"bytes,3,rep,name=trend_data,json=trendData,proto3" json:"trend_data,omitempty"`
	PeakDay       string                 `protobuf:"bytes,4,opt,name=peak_day,json=peakDay,proto3" json:"peak_day,omitempty"`
	PeakHour      string                 `protobuf:"bytes,5,opt,name=peak_hour,json=peakHour,proto3" json:"peak_hour,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevenueAnalytics) Reset() {
	*x = RevenueAnalytics{}
	mi := &file_report_report_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevenueAnalytics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevenueAnalytics) ProtoMessage() {}

func (x *RevenueAnalytics) ProtoReflect() protoreflect.Message {
	mi := &file_report_report_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevenueAnalytics.ProtoReflect.Descriptor instead.
func (*RevenueAnalytics) Descriptor() ([]byte, []int) {
	return file_report_report_proto_rawDescGZIP(), []int{9}
}

func (x *RevenueAnalytics) GetTotalRevenue() float64 {
	if x != nil {
		return x.TotalRevenue
	}
	return 0
}

func (x *RevenueAnalytics) GetGrowthRate() float64 {
	if x != nil {
		return x.GrowthRate
	}
	return 0
}

func (x *RevenueAnalytics) GetTrendData() []*DailySales {
	if x != nil {
		return x.TrendData
	}
	return nil
}

func (x *RevenueAnalytics) GetPeakDay() string {
	if x != nil {
		return x.PeakDay
	}
	return ""
}

func (x *RevenueAnalytics) GetPeakHour() string {
	if x != nil {
		return x.PeakHour
	}
	return ""
}

type GetSalesReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        ReportPeriod           `protobuf:"varint,1,opt,name=period,proto3,enum=report.ReportPeriod" json:"period,omitempty"`
	FromDate      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	ToDate        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSalesReportRequest) Reset() {
	*x = GetSalesReportRequest{}
	mi := &file_report_report_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSalesReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSalesReportRequest) ProtoMessage() {}

func (x *GetSalesReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_report_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSalesReportRequest.ProtoReflect.Descriptor instead.
func (*GetSalesReportRequest) Descriptor() ([]byte, []int) {
	return file_report_report_proto_rawDescGZIP(), []int{10}
}

func (x *GetSalesReportRequest) GetPeriod() ReportPeriod {
	if x != nil {
		return x.Period
	}
	return ReportPeriod_PERIOD_UNKNOWN
}

func (x *GetSalesReportRequest) GetFromDate() *timestamppb.Timestamp {
	if x != nil {
		return x.FromDate
	}
	return nil
}

func (x *GetSalesReportRequest) GetToDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ToDate
	}
	return nil
}

type GetSalesReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *SalesReport           `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSalesReportResponse) Reset() {
	*x = GetSalesReportResponse{}
	mi := &file_report_report_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSalesReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSalesReportResponse) ProtoMessage() {}

func (x *GetSalesReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_report_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSalesReportResponse.ProtoReflect.Descriptor instead.
func (*GetSalesReportResponse) Descriptor() ([]byte, []int) {
	return file_report_report_proto_rawDescGZIP(), []int{11}
}

func (x *GetSalesReportResponse) GetReport() *SalesReport {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *GetSalesReportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetSalesReportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetInventoryReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AsOfDate      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=as_of_date,json=asOfDate,proto3" json:"as_of_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryReportRequest) Reset() {
	*x = GetInventoryReportRequest{}
	mi := &file_report_report_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryReportRequest) ProtoMessage() {}

func (x *GetInventoryReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_report_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryReportRequest.ProtoReflect.Descriptor instead.
func (*GetInventoryReportRequest) Descriptor() ([]byte, []int) {
	return file_report_report_proto_rawDescGZIP(), []int{12}
}

func (x *GetInventoryReportRequest) GetAsOfDate() *timestamppb.Timestamp {
	if x != nil {
		return x.AsOfDate
	}
	return nil
}

type GetInventoryReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *InventoryReport       `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryReportResponse) Reset() {
	*x = GetInventoryReportResponse{}
	mi := &file_report_report_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryReportResponse) ProtoMessage() {}

func (x *GetInventoryReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_report_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryReportResponse.ProtoReflect.Descriptor instead.
func (*GetInventoryReportResponse) Descriptor() ([]byte, []int) {
	return file_report_report_proto_rawDescGZIP(), []int{13}
}

func (x *GetInventoryReportResponse) GetReport() *InventoryReport {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *GetInventoryReportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetInventoryReportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetOrderReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        ReportPeriod           `protobuf:"varint,1,opt,name=period,proto3,enum=report.ReportPeriod" json:"period,omitempty"`
	FromDate      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	ToDate        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderReportRequest) Reset() {
	*x = GetOrderReportRequest{}
	mi := &file_report_report_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderReportRequest) ProtoMessage() {}

func (x *GetOrderReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_report_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderReportRequest.ProtoReflect.Descriptor instead.
func (*GetOrderReportRequest) Descriptor() ([]byte, []int) {
	return file_report_report_proto_rawDescGZIP(), []int{14}
}

func (x *GetOrderReportRequest) GetPeriod() ReportPeriod {
	if x != nil {
		return x.Period
	}
	return ReportPeriod_PERIOD_UNKNOWN
}

func (x *GetOrderReportRequest) GetFromDate() *timestamppb.Timestamp {
	if x != nil {
		return x.FromDate
	}
	return nil
}

func (x *GetOrderReportRequest) GetToDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ToDate
	}
	return nil
}

type GetOrderReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *OrderReport           `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderReportResponse) Reset() {
	*x = GetOrderReportResponse{}
	mi := &file_report_report_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderReportResponse) ProtoMessage() {}

func (x *GetOrderReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_report_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderReportResponse.ProtoReflect.Descriptor instead.
func (*GetOrderReportResponse) Descriptor() ([]byte, []int) {
	return file_report_report_proto_rawDescGZIP(), []int{15}
}

func (x *GetOrderReportResponse) GetReport() *OrderReport {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *GetOrderReportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetOrderReportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetStaffPerformanceReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        ReportPeriod           `protobuf:"varint,1,opt,name=period,proto3,enum=report.ReportPeriod" json:"period,omitempty"`
	FromDate      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	ToDate        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	StaffId       string                 `protobuf:"bytes,4,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStaffPerformanceReportRequest) Reset() {
	*x = GetStaffPerformanceReportRequest{}
	mi := &file_report_report_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStaffPerformanceReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStaffPerformanceReportRequest) ProtoMessage() {}

func (x *GetStaffPerformanceReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_report_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStaffPerformanceReportRequest.ProtoReflect.Descriptor instead.
func (*GetStaffPerformanceReportRequest) Descriptor() ([]byte, []int) {
	return file_report_report_proto_rawDescGZIP(), []int{16}
}

func (x *GetStaffPerformanceReportRequest) GetPeriod() ReportPeriod {
	if x != nil {
		return x.Period
	}
	return ReportPeriod_PERIOD_UNKNOWN
}

func (x *GetStaffPerformanceReportRequest) GetFromDate() *timestamppb.Timestamp {
	if x != nil {
		return x.FromDate
	}
	return nil
}

func (x *GetStaffPerformanceReportRequest) GetToDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ToDate
	}
	return nil
}

func (x *GetStaffPerformanceReportRequest) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

type GetStaffPerformanceReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Performances  []*StaffPerformance    `protobuf:"bytes,1,rep,name=performances,proto3" json:"performances,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStaffPerformanceReportResponse) Reset() {
	*x = GetStaffPerformanceReportResponse{}
	mi := &file_report_report_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStaffPerformanceReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStaffPerformanceReportResponse) ProtoMessage() {}

func (x *GetStaffPerformanceReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_report_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStaffPerformanceReportResponse.ProtoReflect.Descriptor instead.
func (*GetStaffPerformanceReportResponse) Descriptor() ([]byte, []int) {
	return file_report_report_proto_rawDescGZIP(), []int{17}
}

func (x *GetStaffPerformanceReportResponse) GetPerformances() []*StaffPerformance {
	if x != nil {
		return x.Performances
	}
	return nil
}

func (x *GetStaffPerformanceReportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetStaffPerformanceReportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetPopularItemsReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        ReportPeriod           `protobuf:"varint,1,opt,name=period,proto3,enum=report.ReportPeriod" json:"period,omitempty"`
	FromDate      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	ToDate        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	TopN          int32                  `protobuf:"varint,4,opt,name=top_n,json=topN,proto3" json:"top_n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPopularItemsReportRequest) Reset() {
	*x = GetPopularItemsReportRequest{}
	mi := &file_report_report_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPopularItemsReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPopularItemsReportRequest) ProtoMessage() {}

func (x *GetPopularItemsReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_report_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPopularItemsReportRequest.ProtoReflect.Descriptor instead.
func (*GetPopularItemsReportRequest) Descriptor() ([]byte, []int) {
	return file_report_report_proto_rawDescGZIP(), []int{18}
}

func (x *GetPopularItemsReportRequest) GetPeriod() ReportPeriod {
	if x != nil {
		return x.Period
	}
	return ReportPeriod_PERIOD_UNKNOWN
}

func (x *GetPopularItemsReportRequest) GetFromDate() *timestamppb.Timestamp {
	if x != nil {
		return x.FromDate
	}
	return nil
}

func (x *GetPopularItemsReportRequest) GetToDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ToDate
	}
	return nil
}

func (x *GetPopularItemsReportRequest) GetTopN() int32 {
	if x != nil {
		return x.TopN
	}
	return 0
}

type GetPopularItemsReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*PopularItem         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPopularItemsReportResponse) Reset() {
	*x = GetPopularItemsReportResponse{}
	mi := &file_report_report_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPopularItemsReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPopularItemsReportResponse) ProtoMessage() {}

func (x *GetPopularItemsReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_report_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPopularItemsReportResponse.ProtoReflect.Descriptor instead.
func (*GetPopularItemsReportResponse) Descriptor() ([]byte, []int) {
	return file_report_report_proto_rawDescGZIP(), []int{19}
}

func (x *GetPopularItemsReportResponse) GetItems() []*PopularItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetPopularItemsReportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetPopularItemsReportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetRevenueAnalyticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        ReportPeriod           `protobuf:"varint,1,opt,name=period,proto3,enum=report.ReportPeriod" json:"period,omitempty"`
	FromDate      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	ToDate        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRevenueAnalyticsRequest) Reset() {
	*x = GetRevenueAnalyticsRequest{}
	mi := &file_report_report_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRevenueAnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRevenueAnalyticsRequest) ProtoMessage() {}

func (x *GetRevenueAnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_report_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRevenueAnalyticsRequest.ProtoReflect.Descriptor instead.
func (*GetRevenueAnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_report_report_proto_rawDescGZIP(), []int{20}
}

func (x *GetRevenueAnalyticsRequest) GetPeriod() ReportPeriod {
	if x != nil {
		return x.Period
	}
	return ReportPeriod_PERIOD_UNKNOWN
}

func (x *GetRevenueAnalyticsRequest) GetFromDate() *timestamppb.Timestamp {
	if x != nil {
		return x.FromDate
	}
	return nil
}

func (x *GetRevenueAnalyticsRequest) GetToDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ToDate
	}
	return nil
}

type GetRevenueAnalyticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Analytics     *RevenueAnalytics      `protobuf:"bytes,1,opt,name=analytics,proto3" json:"analytics,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRevenueAnalyticsResponse) Reset() {
	*x = GetRevenueAnalyticsResponse{}
	mi := &file_report_report_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRevenueAnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRevenueAnalyticsResponse) ProtoMessage() {}

func (x *GetRevenueAnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_report_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRevenueAnalyticsResponse.ProtoReflect.Descriptor instead.
func (*GetRevenueAnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_report_report_proto_rawDescGZIP(), []int{21}
}

func (x *GetRevenueAnalyticsResponse) GetAnalytics() *RevenueAnalytics {
	if x != nil {
		return x.Analytics
	}
	return nil
}

func (x *GetRevenueAnalyticsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetRevenueAnalyticsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ExportReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportType    string                 `protobuf:"bytes,1,opt,name=report_type,json=reportType,proto3" json:"report_type,omitempty"`
	Format        ExportFormat           `protobuf:"varint,2,opt,name=format,proto3,enum=report.ExportFormat" json:"format,omitempty"`
	Period        ReportPeriod           `protobuf:"varint,3,opt,name=period,proto3,enum=report.ReportPeriod" json:"period,omitempty"`
	FromDate      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	ToDate        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportReportRequest) Reset() {
	*x = ExportReportRequest{}
	mi := &file_report_report_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportReportRequest) ProtoMessage() {}

func (x *ExportReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_report_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportReportRequest.ProtoReflect.Descriptor instead.
func (*ExportReportRequest) Descriptor() ([]byte, []int) {
	return file_report_report_proto_rawDescGZIP(), []int{22}
}

func (x *ExportReportRequest) GetReportType() string {
	if x != nil {
		return x.ReportType
	}
	return ""
}

func (x *ExportReportRequest) GetFormat() ExportFormat {
	if x != nil {
		return x.Format
	}
	return ExportFormat_FORMAT_UNKNOWN
}

func (x *ExportReportRequest) GetPeriod() ReportPeriod {
	if x != nil {
		return x.Period
	}
	return ReportPeriod_PERIOD_UNKNOWN
}

func (x *ExportReportRequest) GetFromDate() *timestamppb.Timestamp {
	if x != nil {
		return x.FromDate
	}
	return nil
}

func (x *ExportReportRequest) GetToDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ToDate
	}
	return nil
}

type ExportReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileData      []byte                 `protobuf:"bytes,1,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportReportResponse) Reset() {
	*x = ExportReportResponse{}
	mi := &file_report_report_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportReportResponse) ProtoMessage() {}

func (x *ExportReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_report_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportReportResponse.ProtoReflect.Descriptor instead.
func (*ExportReportResponse) Descriptor() ([]byte, []int) {
	return file_report_report_proto_rawDescGZIP(), []int{23}
}

func (x *ExportReportResponse) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *ExportReportResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ExportReportResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ExportReportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExportReportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_report_report_proto protoreflect.FileDescriptor

const file_report_report_proto_rawDesc = "" +
	"\n" +
	"\x13report/report.proto\x12\x06report\x1a\x1fgoogle/protobuf/timestamp.proto\"\xec\x02\n" +
	"\vSalesReport\x12\x1f\n" +
	"\vtotal_sales\x18\x01 \x01(\x01R\n" +
	"totalSales\x12\x1b\n" +
	"\ttotal_tax\x18\x02 \x01(\x01R\btotalTax\x12%\n" +
	"\x0etotal_discount\x18\x03 \x01(\x01R\rtotalDiscount\x12\x1f\n" +
	"\vnet_revenue\x18\x04 \x01(\x01R\n" +
	"netRevenue\x12!\n" +
	"\ftotal_orders\x18\x05 \x01(\x05R\vtotalOrders\x12.\n" +
	"\x13average_order_value\x18\x06 \x01(\x01R\x11averageOrderValue\x12;\n" +
	"\x0fdaily_breakdown\x18\a \x03(\v2\x12.report.DailySalesR\x0edailyBreakdown\x12G\n" +
	"\x11payment_breakdown\x18\b \x03(\v2\x1a.report.PaymentMethodSalesR\x10paymentBreakdown\"N\n" +
	"\n" +
	"DailySales\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x14\n" +
	"\x05sales\x18\x02 \x01(\x01R\x05sales\x12\x16\n" +
	"\x06orders\x18\x03 \x01(\x05R\x06orders\"Z\n" +
	"\x12PaymentMethodSales\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"\xd3\x01\n" +
	"\x0fInventoryReport\x122\n" +
	"\x15total_inventory_value\x18\x01 \x01(\x01R\x13totalInventoryValue\x121\n" +
	"\x15low_stock_items_count\x18\x02 \x01(\x05R\x12lowStockItemsCount\x12-\n" +
	"\x05items\x18\x03 \x03(\v2\x17.report.IngredientStockR\x05items\x12*\n" +
	"\x11total_waste_value\x18\x04 \x01(\x01R\x0ftotalWasteValue\"\xf4\x01\n" +
	"\x0fIngredientStock\x12#\n" +
	"\ringredient_id\x18\x01 \x01(\tR\fingredientId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rcurrent_stock\x18\x03 \x01(\x01R\fcurrentStock\x12#\n" +
	"\rminimum_stock\x18\x04 \x01(\x01R\fminimumStock\x12\x1b\n" +
	"\tunit_cost\x18\x05 \x01(\x01R\bunitCost\x12\x1f\n" +
	"\vtotal_value\x18\x06 \x01(\x01R\n" +
	"totalValue\x12 \n" +
	"\fis_low_stock\x18\a \x01(\bR\n" +
	"isLowStock\"\xaa\x02\n" +
	"\vOrderReport\x12!\n" +
	"\ftotal_orders\x18\x01 \x01(\x05R\vtotalOrders\x12)\n" +
	"\x10completed_orders\x18\x02 \x01(\x05R\x0fcompletedOrders\x12)\n" +
	"\x10cancelled_orders\x18\x03 \x01(\x05R\x0fcancelledOrders\x12'\n" +
	"\x0fcompletion_rate\x18\x04 \x01(\x01R\x0ecompletionRate\x128\n" +
	"\x18average_preparation_time\x18\x05 \x01(\x01R\x16averagePreparationTime\x12?\n" +
	"\x10hourly_breakdown\x18\x06 \x03(\v2\x14.report.HourlyOrdersR\x0fhourlyBreakdown\"C\n" +
	"\fHourlyOrders\x12\x12\n" +
	"\x04hour\x18\x01 \x01(\x05R\x04hour\x12\x1f\n" +
	"\vorder_count\x18\x02 \x01(\x05R\n" +
	"orderCount\"\xf5\x01\n" +
	"\x10StaffPerformance\x12\x19\n" +
	"\bstaff_id\x18\x01 \x01(\tR\astaffId\x12\x1d\n" +
	"\n" +
	"staff_name\x18\x02 \x01(\tR\tstaffName\x12%\n" +
	"\x0eorders_handled\x18\x03 \x01(\x05R\rordersHandled\x12\x1f\n" +
	"\vtotal_sales\x18\x04 \x01(\x01R\n" +
	"totalSales\x12.\n" +
	"\x13average_order_value\x18\x05 \x01(\x01R\x11averageOrderValue\x12/\n" +
	"\x13customer_complaints\x18\x06 \x01(\x05R\x12customerComplaints\"\x9e\x01\n" +
	"\vPopularItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1b\n" +
	"\titem_name\x18\x02 \x01(\tR\bitemName\x12#\n" +
	"\rquantity_sold\x18\x03 \x01(\x05R\fquantitySold\x12\x18\n" +
	"\arevenue\x18\x04 \x01(\x01R\arevenue\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\"\xc3\x01\n" +
	"\x10RevenueAnalytics\x12#\n" +
	"\rtotal_revenue\x18\x01 \x01(\x01R\ftotalRevenue\x12\x1f\n" +
	"\vgrowth_rate\x18\x02 \x01(\x01R\n" +
	"growthRate\x121\n" +
	"\n" +
	"trend_data\x18\x03 \x03(\v2\x12.report.DailySalesR\ttrendData\x12\x19\n" +
	"\bpeak_day\x18\x04 \x01(\tR\apeakDay\x12\x1b\n" +
	"\tpeak_hour\x18\x05 \x01(\tR\bpeakHour\"\xb3\x01\n" +
	"\x15GetSalesReportRequest\x12,\n" +
	"\x06period\x18\x01 \x01(\x0e2\x14.report.ReportPeriodR\x06period\x127\n" +
	"\tfrom_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bfromDate\x123\n" +
	"\ato_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06toDate\"y\n" +
	"\x16GetSalesReportResponse\x12+\n" +
	"\x06report\x18\x01 \x01(\v2\x13.report.SalesReportR\x06report\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"U\n" +
	"\x19GetInventoryReportRequest\x128\n" +
	"\n" +
	"as_of_date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\basOfDate\"\x81\x01\n" +
	"\x1aGetInventoryReportResponse\x12/\n" +
	"\x06report\x18\x01 \x01(\v2\x17.report.InventoryReportR\x06report\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xb3\x01\n" +
	"\x15GetOrderReportRequest\x12,\n" +
	"\x06period\x18\x01 \x01(\x0e2\x14.report.ReportPeriodR\x06period\x127\n" +
	"\tfrom_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bfromDate\x123\n" +
	"\ato_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06toDate\"y\n" +
	"\x16GetOrderReportResponse\x12+\n" +
	"\x06report\x18\x01 \x01(\v2\x13.report.OrderReportR\x06report\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xd9\x01\n" +
	" GetStaffPerformanceReportRequest\x12,\n" +
	"\x06period\x18\x01 \x01(\x0e2\x14.report.ReportPeriodR\x06period\x127\n" +
	"\tfrom_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bfromDate\x123\n" +
	"\ato_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06toDate\x12\x19\n" +
	"\bstaff_id\x18\x04 \x01(\tR\astaffId\"\x95\x01\n" +
	"!GetStaffPerformanceReportResponse\x12<\n" +
	"\fperformances\x18\x01 \x03(\v2\x18.report.StaffPerformanceR\fperformances\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xcf\x01\n" +
	"\x1cGetPopularItemsReportRequest\x12,\n" +
	"\x06period\x18\x01 \x01(\x0e2\x14.report.ReportPeriodR\x06period\x127\n" +
	"\tfrom_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bfromDate\x123\n" +
	"\ato_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06toDate\x12\x13\n" +
	"\x05top_n\x18\x04 \x01(\x05R\x04topN\"~\n" +
	"\x1dGetPopularItemsReportResponse\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.report.PopularItemR\x05items\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xb8\x01\n" +
	"\x1aGetRevenueAnalyticsRequest\x12,\n" +
	"\x06period\x18\x01 \x01(\x0e2\x14.report.ReportPeriodR\x06period\x127\n" +
	"\tfrom_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bfromDate\x123\n" +
	"\ato_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06toDate\"\x89\x01\n" +
	"\x1bGetRevenueAnalyticsResponse\x126\n" +
	"\tanalytics\x18\x01 \x01(\v2\x18.report.RevenueAnalyticsR\tanalytics\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x80\x02\n" +
	"\x13ExportReportRequest\x12\x1f\n" +
	"\vreport_type\x18\x01 \x01(\tR\n" +
	"reportType\x12,\n" +
	"\x06format\x18\x02 \x01(\x0e2\x14.report.ExportFormatR\x06format\x12,\n" +
	"\x06period\x18\x03 \x01(\x0e2\x14.report.ReportPeriodR\x06period\x127\n" +
	"\tfrom_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bfromDate\x123\n" +
	"\ato_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x06toDate\"\xa7\x01\n" +
	"\x14ExportReportResponse\x12\x1b\n" +
	"\tfile_data\x18\x01 \x01(\fR\bfileData\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage*\x81\x01\n" +
	"\fReportPeriod\x12\x12\n" +
	"\x0ePERIOD_UNKNOWN\x10\x00\x12\x10\n" +
	"\fPERIOD_DAILY\x10\x01\x12\x11\n" +
	"\rPERIOD_WEEKLY\x10\x02\x12\x12\n" +
	"\x0ePERIOD_MONTHLY\x10\x03\x12\x11\n" +
	"\rPERIOD_YEARLY\x10\x04\x12\x11\n" +
	"\rPERIOD_CUSTOM\x10\x05*e\n" +
	"\fExportFormat\x12\x12\n" +
	"\x0eFORMAT_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"FORMAT_PDF\x10\x01\x12\x10\n" +
	"\fFORMAT_EXCEL\x10\x02\x12\x0e\n" +
	"\n" +
	"FORMAT_CSV\x10\x03\x12\x0f\n" +
	"\vFORMAT_JSON\x10\x042\x91\x05\n" +
	"\rReportService\x12O\n" +
	"\x0eGetSalesReport\x12\x1d.report.GetSalesReportRequest\x1a\x1e.report.GetSalesReportResponse\x12[\n" +
	"\x12GetInventoryReport\x12!.report.GetInventoryReportRequest\x1a\".report.GetInventoryReportResponse\x12O\n" +
	"\x0eGetOrderReport\x12\x1d.report.GetOrderReportRequest\x1a\x1e.report.GetOrderReportResponse\x12p\n" +
	"\x19GetStaffPerformanceReport\x12(.report.GetStaffPerformanceReportRequest\x1a).report.GetStaffPerformanceReportResponse\x12d\n" +
	"\x15GetPopularItemsReport\x12$.report.GetPopularItemsReportRequest\x1a%.report.GetPopularItemsReportResponse\x12^\n" +
	"\x13GetRevenueAnalytics\x12\".report.GetRevenueAnalyticsRequest\x1a#.report.GetRevenueAnalyticsResponse\x12I\n" +
	"\fExportReport\x12\x1b.report.ExportReportRequest\x1a\x1c.report.ExportReportResponseB$Z\"restaurant-management/proto/reportb\x06proto3"

var (
	file_report_report_proto_rawDescOnce sync.Once
	file_report_report_proto_rawDescData []byte
)

func file_report_report_proto_rawDescGZIP() []byte {
	file_report_report_proto_rawDescOnce.Do(func() {
		file_report_report_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_report_report_proto_rawDesc), len(file_report_report_proto_rawDesc)))
	})
	return file_report_report_proto_rawDescData
}

var file_report_report_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_report_report_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_report_report_proto_goTypes = []any{
	(ReportPeriod)(0),                         // 0: report.ReportPeriod
	(ExportFormat)(0),                         // 1: report.ExportFormat
	(*SalesReport)(nil),                       // 2: report.SalesReport
	(*DailySales)(nil),                        // 3: report.DailySales
	(*PaymentMethodSales)(nil),                // 4: report.PaymentMethodSales
	(*InventoryReport)(nil),                   // 5: report.InventoryReport
	(*IngredientStock)(nil),                   // 6: report.IngredientStock
	(*OrderReport)(nil),                       // 7: report.OrderReport
	(*HourlyOrders)(nil),                      // 8: report.HourlyOrders
	(*StaffPerformance)(nil),                  // 9: report.StaffPerformance
	(*PopularItem)(nil),                       // 10: report.PopularItem
	(*RevenueAnalytics)(nil),                  // 11: report.RevenueAnalytics
	(*GetSalesReportRequest)(nil),             // 12: report.GetSalesReportRequest
	(*GetSalesReportResponse)(nil),            // 13: report.GetSalesReportResponse
	(*GetInventoryReportRequest)(nil),         // 14: report.GetInventoryReportRequest
	(*GetInventoryReportResponse)(nil),        // 15: report.GetInventoryReportResponse
	(*GetOrderReportRequest)(nil),             // 16: report.GetOrderReportRequest
	(*GetOrderReportResponse)(nil),            // 17: report.GetOrderReportResponse
	(*GetStaffPerformanceReportRequest)(nil),  // 18: report.GetStaffPerformanceReportRequest
	(*GetStaffPerformanceReportResponse)(nil), // 19: report.GetStaffPerformanceReportResponse
	(*GetPopularItemsReportRequest)(nil),      // 20: report.GetPopularItemsReportRequest
	(*GetPopularItemsReportResponse)(nil),     // 21: report.GetPopularItemsReportResponse
	(*GetRevenueAnalyticsRequest)(nil),        // 22: report.GetRevenueAnalyticsRequest
	(*GetRevenueAnalyticsResponse)(nil),       // 23: report.GetRevenueAnalyticsResponse
	(*ExportReportRequest)(nil),               // 24: report.ExportReportRequest
	(*ExportReportResponse)(nil),              // 25: report.ExportReportResponse
	(*timestamppb.Timestamp)(nil),             // 26: google.protobuf.Timestamp
}
var file_report_report_proto_depIdxs = []int32{
	3,  // 0: report.SalesReport.daily_breakdown:type_name -> report.DailySales
	4,  // 1: report.SalesReport.payment_breakdown:type_name -> report.PaymentMethodSales
	6,  // 2: report.InventoryReport.items:type_name -> report.IngredientStock
	8,  // 3: report.OrderReport.hourly_breakdown:type_name -> report.HourlyOrders
	3,  // 4: report.RevenueAnalytics.trend_data:type_name -> report.DailySales
	0,  // 5: report.GetSalesReportRequest.period:type_name -> report.ReportPeriod
	26, // 6: report.GetSalesReportRequest.from_date:type_name -> google.protobuf.Timestamp
	26, // 7: report.GetSalesReportRequest.to_date:type_name -> google.protobuf.Timestamp
	2,  // 8: report.GetSalesReportResponse.report:type_name -> report.SalesReport
	26, // 9: report.GetInventoryReportRequest.as_of_date:type_name -> google.protobuf.Timestamp
	5,  // 10: report.GetInventoryReportResponse.report:type_name -> report.InventoryReport
	0,  // 11: report.GetOrderReportRequest.period:type_name -> report.ReportPeriod
	26, // 12: report.GetOrderReportRequest.from_date:type_name -> google.protobuf.Timestamp
	26, // 13: report.GetOrderReportRequest.to_date:type_name -> google.protobuf.Timestamp
	7,  // 14: report.GetOrderReportResponse.report:type_name -> report.OrderReport
	0,  // 15: report.GetStaffPerformanceReportRequest.period:type_name -> report.ReportPeriod
	26, // 16: report.GetStaffPerformanceReportRequest.from_date:type_name -> google.protobuf.Timestamp
	26, // 17: report.GetStaffPerformanceReportRequest.to_date:type_name -> google.protobuf.Timestamp
	9,  // 18: report.GetStaffPerformanceReportResponse.performances:type_name -> report.StaffPerformance
	0,  // 19: report.GetPopularItemsReportRequest.period:type_name -> report.ReportPeriod
	26, // 20: report.GetPopularItemsReportRequest.from_date:type_name -> google.protobuf.Timestamp
	26, // 21: report.GetPopularItemsReportRequest.to_date:type_name -> google.protobuf.Timestamp
	10, // 22: report.GetPopularItemsReportResponse.items:type_name -> report.PopularItem
	0,  // 23: report.GetRevenueAnalyticsRequest.period:type_name -> report.ReportPeriod
	26, // 24: report.GetRevenueAnalyticsRequest.from_date:type_name -> google.protobuf.Timestamp
	26, // 25: report.GetRevenueAnalyticsRequest.to_date:type_name -> google.protobuf.Timestamp
	11, // 26: report.GetRevenueAnalyticsResponse.analytics:type_name -> report.RevenueAnalytics
	1,  // 27: report.ExportReportRequest.format:type_name -> report.ExportFormat
	0,  // 28: report.ExportReportRequest.period:type_name -> report.ReportPeriod
	26, // 29: report.ExportReportRequest.from_date:type_name -> google.protobuf.Timestamp
	26, // 30: report.ExportReportRequest.to_date:type_name -> google.protobuf.Timestamp
	12, // 31: report.ReportService.GetSalesReport:input_type -> report.GetSalesReportRequest
	14, // 32: report.ReportService.GetInventoryReport:input_type -> report.GetInventoryReportRequest
	16, // 33: report.ReportService.GetOrderReport:input_type -> report.GetOrderReportRequest
	18, // 34: report.ReportService.GetStaffPerformanceReport:input_type -> report.GetStaffPerformanceReportRequest
	20, // 35: report.ReportService.GetPopularItemsReport:input_type -> report.GetPopularItemsReportRequest
	22, // 36: report.ReportService.GetRevenueAnalytics:input_type -> report.GetRevenueAnalyticsRequest
	24, // 37: report.ReportService.ExportReport:input_type -> report.ExportReportRequest
	13, // 38: report.ReportService.GetSalesReport:output_type -> report.GetSalesReportResponse
	15, // 39: report.ReportService.GetInventoryReport:output_type -> report.GetInventoryReportResponse
	17, // 40: report.ReportService.GetOrderReport:output_type -> report.GetOrderReportResponse
	19, // 41: report.ReportService.GetStaffPerformanceReport:output_type -> report.GetStaffPerformanceReportResponse
	21, // 42: report.ReportService.GetPopularItemsReport:output_type -> report.GetPopularItemsReportResponse
	23, // 43: report.ReportService.GetRevenueAnalytics:output_type -> report.GetRevenueAnalyticsResponse
	25, // 44: report.ReportService.ExportReport:output_type -> report.ExportReportResponse
	38, // [38:45] is the sub-list for method output_type
	31, // [31:38] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_report_report_proto_init() }
func file_report_report_proto_init() {
	if File_report_report_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_report_report_proto_rawDesc), len(file_report_report_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_report_report_proto_goTypes,
		DependencyIndexes: file_report_report_proto_depIdxs,
		EnumInfos:         file_report_report_proto_enumTypes,
		MessageInfos:      file_report_report_proto_msgTypes,
	}.Build()
	File_report_report_proto = out.File
	file_report_report_proto_goTypes = nil
	file_report_report_proto_depIdxs = nil
}
